[000]
title = "Build on, interface with, or extend the Qiskit in a meaningful way"
description = "Software in the Qiskit Ecosystem should related to Qiskit projects in some meaningful way. Software that manipulate Qiskit data structure (such as transpiler plugins) are good examples of that. If the connection with Qiskit is not that obvious, consider having a tutorial or how-to guide explaining a use-case for Qiskit users."
applies_to = "all"
category = "SUBMISSION"
importance = "CRITICAL"

[010]
title = "member.name should not include the substring 'test'"
description = "Projects in the Qiskit Ecosystem should related"
applies_to = "all"
affects = "member.name"
category = "SUBMISSION"
checker = "test_name.py::test_valid_name_no_test_substring"
importance = "RECOMENDATION"

[[importance]]
name = "CRITICAL"
description = "This is a must."

[[importance]]
name = "RECOMENDATION"
description = "This is a recomendation."

[[categories]]
name = "SUBMISSION"
description = "Validations done one time when a project is submitted."

[[categories]]
name = "METADATA"
description = "There is an issue about the member metadata used in the ecosystem. It is not an upstream error."

[[categories]]
name = "GENERAL"
description = """General criteria that might be implemented differently, depending on the project. Check the "related to" validations to see which might apply to a specific repository, software, or package."""

[[categories]]
name = "ACTIVITY"
description = "The project might not have a level of activity to be considered well-maintained."

[[categories]]
name = "OSS"
description = "There is an issue with some of the open-source aspect of the project."

[[categories]]
name = "OUT-OF-DATE"
description = "The project might not follow the last best-practices or connects to Qiskit in a way that is considered old-fashioned, currently unsupported, or deprecated."