site_name: Qiskit Ecosystem documentation
site_url: https://qiskit.github.io/ecosystem/

theme:
  name: material
  palette:
    primary: deep purple
  logo: img/logo.png
  favicon: img/favicon.ico
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - table-reader

nav:
  - Classifications:
    - Status: status.md
    - Categories: categories.md
    - Labels: labels.md
    - Qiskit Pattern steps: pattern_steps.md
    - Interfaces: interfaces.md
    - Maturity levels: maturity.md
  - Badges: badges.md
