[tox]
minversion = 3.9
envlist = py313, lint, coverage, black
skipsdist = True

[testenv]
basepython = python3.13
usedevelop = true
passenv = *
install_command = pip install -U {opts} {packages}
setenv =
  VIRTUAL_ENV={envdir}
  LANGUAGE=en_US
  LC_ALL=en_US.utf-8
deps = -r requirements.txt
       -r requirements-dev.txt
commands =
  pip check
  python -m unittest -v

[testenv:lint]
envdir = .tox/lint
sitepackages = False
commands =
  pylint -rn ecosystem tests

[testenv:coverage]
basepython = python3
commands =
  coverage3 run -m unittest -v
  coverage3 report

[testenv:black]
envdir = .tox/lint
commands = black {posargs} ecosystem tests --check

[testenv:website]
allowlist_externals =
  bash
basepython = python3
commands =
  bash -ec "python -m pip install . --force-reinstall"
  bash -ec "python manager.py members create_badge_endpoints -o b/"
  bash -ec "python manager.py members update_docs_assets"
  bash -ec "mkdocs build -d website/"
  bash -ec "python manager.py build --output website/index.html"
  bash -ec "mv b/ website/"
  bash -ec "python manager.py members compile_json 'website/ecosystem.json'"
