[[categories]]
name = "SDK"
description = "A software development kit. Provides an interface to build software on top of it. "

[[categories]]
name = "Application"
description = "Helps run or work with higher-than-circuit or domain-specifc level of abstraction."

[[categories]]
name = "Tooling"
description = "Helps to develop quantum programs, such as IDEs, debuggers, or other development tooling."

[[categories]]
name = "Compute provider"
description = "Provides access to remote quantum computers (or remote simulators) via Qiskit primitives"

[[categories]]
name = "Circuit simulator"
description = "Simulates a quantum computer on your local classical computer"

[[categories]]
name = "Transpiler plugin"
description = "Implements Qiskit's transpiler plugin interface"

[[categories]]
name = "Converter"
description = "Converts Qiskit objects (such as QuantumCircuit) for use in other programs or tools"

[[categories]]
name = "Qiskit addon"
description = "Enables algorithm discovery at the utility scale"

[[categories]]
name = "Game"
description = "Games or playful educational resources"

[[categories]]
name = "Paper artifact"
description = "Code or dataset needed to reproduce a specific paper. Probably, without long-term support."

[[categories]]
name = "Other"
description = "Projects that extend, interface with, or use Qiskit in interesting ways"

[[labels]]
name = "chemistry"
description = "Applies quantum computing to chemistry"

[[labels]]
name = "error correction"
description = "Performs or investigates quantum error correction"

[[labels]]
name = "error mitigation"
description = "Tools for mitigating errors"

[[labels]]
name = "finance"
description = "Applies quantum computing to finance"

[[labels]]
name = "QML"
description = "Applies quantum computing to machine learning"

[[labels]]
name = "optimization"
description = "Applies quantum computing to optimization problems"

[[labels]]
name = "physics"
description = "Applies quantum computing to physics"

[[labels]]
name = "provider"
description = "Implements a Qiskit provider or/and Qiskit primitives"
link = "https://quantum.cloud.ibm.com/docs/en/api/qiskit/providers"

[[labels]]
name = "cloud service"
description = "Requieres an account in a cloud service."

[[labels]]
name = "HPC"
description = "Targets High-Performance Computing use-cases."

[[labels]]
name = "quantum information"
description = "Tools for quantum information experiments"

[[labels]]
name = "research"
description = "Implements ideas from papers and/or cutting-edge research"

[[labels]]
name = "demo"
description = "Implements a demo or a proof of concept."

[[labels]]
name = "circuit building"
description = "Builds and outputs Qiskit quantum circuits."

[[labels]]
name = "circuit optimization"
description = "Optimizes Qiskit quantum circuits."

[[labels]]
name = "unitary synthesis"
description = "Synthesizes unitary operations into quantum circuits or operations."

[[labels]]
name = "high-level synthesis"
description = "Synthesizes quantum circuits or operations from more abstract operation boxes."

[[labels]]
name = "openqasm"
description = "Interfaces with OpenQASM."

[[interfaces]]
name = "Python"
description = "API callable from Python programming language"

[[interfaces]]
name = "C"
description = "API callable from C programming language"

[[interfaces]]
name = "C++"
description = "API callable from C++ programming language"

[[interfaces]]
name = "Julia"
description = "API callable from Julia programming language"

[[interfaces]]
name = "Rust"
description = "API callable from Rust programming language"

[[interfaces]]
name = "OCaml"
description = "API callable from OCaml programming language"

[[interfaces]]
name = "Java"
description = "API callable from Java programming language"

[[interfaces]]
name = "Other language"
description = "API callable from a programming language not yet listed "

[[interfaces]]
name = "Command-line interface (CLI)"
description = "Software can be used from the command-line as a standalone program"

[[interfaces]]
name = "Graphical User Interface (GUI)"
description = "Software can be used from a graphical inteface, as standalone program"

[[interfaces]]
name = "Web interface"
description = "Software has a web inteface"

[[interfaces]]
name = "Web interface"
description = "Software has a web inteface"

[[interfaces]]
name = "Other interface"
description = "The way to interact with this software is not listed yet"

[[status]]
name = "Qiskit Project"
description = "Approved Qiskt Project"

[[status]]
name = "Member"
description = "The project is an approved member of the Qiskit Ecosystem"

[[status]]
name = "Under review"
description = "The project needs to review some of the check up issues to stay in the Qiskit Ecosystem"

[[status]]
name = "Alumni"
description = "The project used to be part of the Qiskit Ecosystem"

[[support]]
name = "stable"
description = "The project is actively maintained and the code is considered stable. Recommended for production."

[[support]]
name = "archived"
description = "The project is no longer supported and the code repository is archived."
show_in_submission_template = false

[[support]]
name = "abandoned"
description = "The project appears to be abandoned, as there has been no activity in the last 2 years."
show_in_submission_template = false

[[support]]
name = "outdated"
description = "The project does not run with supported versions of Qiskit."
show_in_submission_template = false

[[support]]
name = "experimental"
description = "The project is under active development and breaking changes may be introduced at any point. Use in production with caution."

[[support]]
name = "bugfixing only"
description = "The project is minimally maintained. Bugs are fixed and dependencies are kept up to date, but no new features are planned."

[[support]]
name = "as-is"
description = "The project has no active maintenance expectations."

[[support]]
name = "deprecated"
description = "The project still functional but no longer recommended for use."
show_in_submission_template = false
