name: 🔄 Update request
description: Update (or remove) information about your project
title: "[Project update]: "
labels: [member update]
body:
  - type: markdown
    attributes:
      value: |
        Explain the update you are requesting.
        You can also request a removal.
        In any case, feel free to cancel this issue submission and open a PR directly with your suggested changes.
        You may also open a PR later to address this issue.
        The PR should modify a single file in https://github.com/Qiskit/ecosystem/blob/main/ecosystem/resources/members
  - type: input
    id: member_name
    attributes:
      label: Project name
      description: |
        Name of the Ecosystem project to update or remove.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Mention the field you would like to update and describe the new value.
        If you are requesting removal, explain why you would like the project to be removed from the ecosystem.
      placeholder: e.g. The documentation moved to https://docs.bananaproject.org
    validations:
      required: true
