name: 🔄 Update request
description: Update (or remove) information about your project
title: "[Project update]: "
labels: [member update]
body:
  - type: markdown
    attributes:
      value: |
        Explain the update you are requesting. You can also request a removal. In anycase, feel free to cancel this issue submission and open a PR directly with your suggested changes. You can also open a PR to address this issue later. The PR should modify a single file in https://github.com/Qiskit/ecosystem/blob/main/ecosystem/resources/members
  - type: input
    id: member_id
    attributes:
      label: Project name
      description: |
        Name of Ecosytem project to update or remove.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Mention the field you'd like to update, and tell us what you'd like to update the field to. You can also explain why you would like to remove a project from the ecosystem, if that is the case.
      placeholder: e.g. The documentation got moved to https://docs.bananaproject.org
    validations:
      required: true
