name = "Qiskit_Advocate_Ecosystem"
submission_number = 1336
url = "https://github.com/drjssk6"
description = "develop circuit and bugs fixing"
contact_info = "drjssk6@gmail.com"
labels = []
interfaces = ["Python"]
category = "SDK"
packages = []
uuid = "f14e032e-fc34-44c5-a9de-b48bc04cafc0"
maturity = "as-is"
