name = "Qiskit_Advocate_Ecosystem"
submission_number = 1336
url = "https://github.com/drjssk6"
description = "develop circuit and bugs fixing"
contact_info = "drjssk6@gmail.com"
labels = []
interfaces = ["Python"]
category = "SDK"
packages = []
uuid = "fd2253d5-1556-44b3-ac7e-1ad1f90b5e72"
maturity = "as-is"
