name = "Aer"
url = "https://github.com/Qiskit/qiskit-aer"
description = "High-performance quantum computing simulators with realistic noise models."
license = "Apache 2.0"
labels = ["provider"]
interfaces = ["Python", "C++"]
ibm_maintained = true
created_at = 2021-11-08
category = "Circuit simulator"
pattern_steps = ["Execute"]
documentation = "https://qiskit.github.io/qiskit-aer/"
packages = []
uuid = "474599a7-228b-446f-ae57-636fdbe8c1c6"
maturity = "bugfixing only"
status = "Qiskit Project"

[github]
url = "https://github.com/Qiskit/qiskit-aer"
owner = "Qiskit"
repo = "qiskit-aer"
stars = 675
homepage = "https://qiskit.github.io/qiskit-aer/"
license = "Apache License 2.0"
description = "Aer is a high performance simulator for quantum circuits that includes noise models"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-05-25
last_activity = 2026-07-02

[badge]
url = "https://qisk.it/e-474599a7"
style = "flat"

[pypi.qiskit-aer]
package_name = "qiskit-aer"
version = "0.17.2"
last_release_date = 2026-02-04
description = "Aer - High performance simulators for Qiskit"
url = "https://pypi.org/project/qiskit-aer/"
requires_qiskit = ">=1.1.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 600188
last_180_days_downloads = 3216237

[pypi.qiskit-aer-gpu]
package_name = "qiskit-aer-gpu"
version = "0.15.1"
last_release_date = 2024-09-13
description = "Aer - High performance simulators for Qiskit"
url = "https://pypi.org/project/qiskit-aer-gpu/"
requires_qiskit = ">=1.1.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 4765
last_180_days_downloads = 26764

[pypi.qiskit-aer-gpu-cu11]
package_name = "qiskit-aer-gpu-cu11"
version = "0.17.2"
last_release_date = 2025-09-17
description = "Aer - High performance simulators for Qiskit"
url = "https://pypi.org/project/qiskit-aer-gpu-cu11/"
requires_qiskit = ">=1.1.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 1529
last_180_days_downloads = 12792
