name = "Aer"
url = "https://github.com/Qiskit/qiskit-aer"
description = "High-performance quantum computing simulators with realistic noise models."
license = "Apache-2.0"
labels = ["provider", "HPC", "GPU"]
interfaces = ["Python", "C++"]
ibm_maintained = true
created_at = 2021-11-08
category = "Circuit simulator"
pattern_steps = ["Execute"]
documentation = "https://qiskit.github.io/qiskit-aer/"
packages = []
uuid = "474599a7-228b-446f-ae57-636fdbe8c1c6"
maturity = "bugfixing only"
status = "Qiskit Project"

[github]
url = "https://github.com/Qiskit/qiskit-aer"
owner = "Qiskit"
repo = "qiskit-aer"
stars = 680
homepage = "https://qiskit.github.io/qiskit-aer/"
license = "Apache-2.0"
description = "Aer is a high performance simulator for quantum circuits that includes noise models"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-05-25
last_activity = 2026-07-17

[badge]
url = "https://qisk.it/e-474599a7"
style = "flat"

[pypi.qiskit-aer]
package_name = "qiskit-aer"
version = "0.17.2"
last_release_date = 2026-02-04
license = "Apache-2.0"
description = "Aer - High performance simulators for Qiskit"
url = "https://pypi.org/project/qiskit-aer/"
status = "active"
maintainers = ["https://pypi.org/org/qiskit/"]
requires_qiskit = ">=1.1.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 692163
last_180_days_downloads = 3461907

[pypi.qiskit-aer-gpu]
package_name = "qiskit-aer-gpu"
version = "0.15.1"
last_release_date = 2024-09-13
license = "Apache-2.0"
description = "Aer - High performance simulators for Qiskit"
url = "https://pypi.org/project/qiskit-aer-gpu/"
status = "active"
maintainers = ["https://pypi.org/org/qiskit/"]
requires_qiskit = ">=1.1.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 5045
last_180_days_downloads = 27575

[pypi.qiskit-aer-gpu-cu11]
package_name = "qiskit-aer-gpu-cu11"
version = "0.17.2"
last_release_date = 2025-09-17
license = "Apache-2.0"
description = "Aer - High performance simulators for Qiskit"
url = "https://pypi.org/project/qiskit-aer-gpu-cu11/"
status = "active"
maintainers = ["https://pypi.org/org/qiskit/"]
requires_qiskit = ">=1.1.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 1629
last_180_days_downloads = 12354

[checks.P10]
since = 2026-07-14
details = "Python package qiskit-aer declared itself compatible to a not-yet-released major version of Qiskit"
importance = "RECOMMENDATION"
