name = "Qiskit Algorithms"
url = "https://github.com/qiskit-community/qiskit-algorithms"
description = "A library of quantum algorithms for near-term quantum devices with short-depth circuits."
license = "Apache-2.0"
contact_info = "ept@zurich.ibm.com"
affiliations = "IBM Quantum"
labels = []
interfaces = ["Python"]
category = "Application"
documentation = "https://qiskit-community.github.io/qiskit-algorithms/"
packages = []
uuid = "39fba621-edbb-485b-a723-8a0760ab4b85"
maturity = "production-ready"

[github]
url = "https://github.com/qiskit-community/qiskit-algorithms"
owner = "qiskit-community"
repo = "qiskit-algorithms"
stars = 186
homepage = "https://qiskit-community.github.io/qiskit-algorithms/"
license = "Apache-2.0"
description = "A library of quantum algorithms for Qiskit."
total_dependent_repositories = 568
total_dependent_packages = 59
last_commit = 2026-06-19
last_activity = 2026-07-12

[badge]
url = "https://qisk.it/e-39fba621"
style = "flat"

[pypi.qiskit-algorithms]
package_name = "qiskit-algorithms"
version = "0.4.0"
last_release_date = 2025-08-29
license = "Apache-2.0"
description = "Qiskit Algorithms: A library of quantum computing algorithms"
url = "https://pypi.org/project/qiskit-algorithms/"
status = "active"
maintainers = ["https://pypi.org/org/qiskit/"]
requires_qiskit = ">=1.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 207351
last_180_days_downloads = 564142

[checks.P10]
since = 2026-07-09
details = "Python package qiskit-algorithms declared itself compatible to a not-yet-released major version of Qiskit"
importance = "RECOMMENDATION"
