name = "Alice & Bob Qiskit provider"
url = "https://github.com/Alice-Bob-SW/qiskit-alice-bob-provider"
description = "Access Alice & Bob QPUs and emulators using Qiskit."
license = "Apache 2.0"
labels = ["cloud service"]
interfaces = ["Python"]
created_at = 2024-05-07
category = "Compute provider"
documentation = "https://felis.alice-bob.com/docs/"
packages = []
uuid = "00f82ee3-ab46-44fc-afbb-32cb34a72339"
maturity = "production-ready"
status = "Under revision"

[github]
url = "https://github.com/Alice-Bob-SW/qiskit-alice-bob-provider"
owner = "Alice-Bob-SW"
repo = "qiskit-alice-bob-provider"
stars = 45
homepage = "https://felis.alice-bob.com/docs/"
license = "Apache License 2.0"
description = "Qiskit provider to execute quantum circuits on Alice & Bob cat qubits"
estimated_contributors = 8
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-06-08
last_activity = 2026-06-08

[badge]
url = "https://qisk.it/e-00f82ee3"
style = "flat"

[checks.PQ2]
since = 2026-04-30T11:32:49.789583
details = "Python package qiskit-alice-bob-provider is not compatible with Qiskit SDK v2"
discussion = "https://github.com/Alice-Bob-SW/qiskit-alice-bob-provider/issues/80"
importance = "IMPORTANT"

[pypi.qiskit-alice-bob-provider]
package_name = "qiskit-alice-bob-provider"
version = "1.2.0"
last_release_date = 2025-03-27
description = "Provider for running Qiskit circuits on Alice & Bob QPUs and simulators"
url = "https://pypi.org/project/qiskit-alice-bob-provider/"
requires_qiskit = "<2.0,>=1.3.1"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = false
highest_supported_qiskit_release_date = 2025-10-13
highest_supported_qiskit_version = "1.4.5"
last_month_downloads = 741
last_180_days_downloads = 1948
