name = "Qiskit Braket provider"
url = "https://github.com/qiskit-community/qiskit-braket-provider"
description = "Execute Qiskit programs on AWS quantum computing hardware devices through Amazon Braket."
license = "Apache 2.0"
labels = [ "provider", "cloud service",]
interfaces = [ "Python",]
created_at = 2024-05-07
category = "Compute provider"
documentation = "https://qiskit-braket-provider.readthedocs.io/"
packages = []
uuid = "de20c734-6ee9-4ba0-a4f0-3e4d62ec3c2a"
maturity = "production-ready"

[github]
url = "https://github.com/amazon-braket/qiskit-braket-provider"
owner = "amazon-braket"
repo = "qiskit-braket-provider"
stars = 83
homepage = "https://qiskit-braket-provider.readthedocs.io/"
license = "Other"
description = "Qiskit-Braket provider to execute Qiskit programs on devices via Amazon Braket."
estimated_contributors = 41
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-07-02
last_activity = 2026-07-04

[badge]
url = "https://qisk.it/e-de20c734"
style = "flat"

[pypi.qiskit-braket-provider]
package_name = "qiskit-braket-provider"
version = "0.17.3"
last_release_date = 2026-03-12
license = "Apache Software License"
description = "Qiskit-Braket provider to execute Qiskit programs on devices via Amazon Braket."
url = "https://pypi.org/project/qiskit-braket-provider/"
status = "active"
maintainers = [ "https://pypi.org/user/amazonbraket/",]
requires_qiskit = ">=2.0.0"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 15471
last_180_days_downloads = 50308
