name = "CALA-n Quantum Library"
url = "https://github.com/albayaty/cala_quantum_library"
description = "A set of cost-effective n-bit gates based on Clifford+T gates, quantum layouts, and n neighboring physical qubits (2 <= n <= 5)."
license = "Apache-2.0"
contact_info = "albayaty@pdx.edu"
affiliations = "Department of Electrical and Computer Engineering at Portland State University"
labels = ["circuit optimization", "research", "circuit building"]
interfaces = ["Python"]
category = "Application"
reference_paper = "https://doi.org/10.48550/arXiv.2408.01025"
packages = []
uuid = "8868c7af-adce-48ee-9ca9-d066fb569cf4"
maturity = "production-ready"

[github]
url = "https://github.com/albayaty/cala_quantum_library"
owner = "albayaty"
repo = "cala_quantum_library"
stars = 1
license = "Apache-2.0"
description = "CALA-n Quantum Library"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2024-10-20
last_activity = 2026-01-20

[badge]
url = "https://qisk.it/e-8868c7af"
style = "flat"

[checks.G07]
since = 2026-05-14
details = "Last commit was 20 months ago, which is more than 18 months ago. Please update the GitHub repository or set member.maturity to `as-is`."
importance = "STRONG-RECOMMENDATION"
