name = "Qiskit Cayley Codes"
submission_number = 1320
url = "https://github.com/RexRowan/Qiskit-Cayley-Codes"
description = "Cayley-graph construction and exploration of quantum LDPC codes in Qiskit"
contact_info = "titaniumdavinci@gmail.com"
labels = ["quantum information", "research"]
interfaces = ["Python"]
category = "Tooling"
reference_paper = "https://ieeexplore.ieee.org/document/6560408"
packages = []
uuid = "ccc8f071-ad3d-47f9-af61-319e739a2c8f"
maturity = "experimental"

[github]
owner = "RexRowan"
repo = "Qiskit-Cayley-Codes"

[pypi.qiskit-cayley-codes]
package_name = "qiskit-cayley-codes"
