name = "dense-ev"
url = "https://github.com/atlytle/dense-ev"
description = "Expectation value measurements in Qiskit using optimal dense grouping, an improvement of (3/2)^m over qubit-wise commuting groups."
license = "Apache License 2.0"
contact_info = "atlytle@gmail.com"
affiliations = "University of Illinois at Urbana-Champaign"
labels = []
interfaces = [ "Python",]
category = "Paper artifact"
reference_paper = "https://arxiv.org/abs/2305.11847"
packages = []
uuid = "f305aa07-74a6-4af4-bb80-e0a75672f16f"
maturity = "production-ready"
status = "Under revision"

[github]
url = "https://github.com/atlytle/dense-ev"
owner = "atlytle"
repo = "dense-ev"
stars = 12
license = "Apache License 2.0"
description = "Expectation value measurements in Qiskit using optimal dense grouping. Dense-ev provides an improvement of ~2^m over naive grouping..."
estimated_contributors = 2
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2024-05-30
last_activity = 2026-06-16

[badge]
url = "https://qisk.it/e-f305aa07"
style = "flat"

[checks.PQ2]
since = 2026-04-30T11:32:49.789583
details = "Python package dense-ev is not compatible with Qiskit SDK v2"
importance = "IMPORTANT"

[pypi.dense-ev]
package_name = "dense-ev"
version = "2023.5.22"
last_release_date = 2023-05-21
description = "Qiskit expectation values using optimal dense grouping."
url = "https://pypi.org/project/dense-ev/"
requires_qiskit = "<0.43.0"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = false
highest_supported_qiskit_release_date = 2023-03-21
highest_supported_qiskit_version = "0.42.1"
last_month_downloads = 63
last_180_days_downloads = 231
