name = "Device Benchmarking"
submission_number = 1348
url = "https://github.com/qiskit-community/qiskit-device-benchmarking"
description = "Notebooks and libraries built on Qiskit Experiments for benchmarking device performance: layer fidelity, quantum volume, CLOPS."
labels = ["benchmarking", "quantum information", "research"]
interfaces = ["Python", "Command-line interface (CLI)"]
category = "Tooling"
packages = []
uuid = "83d79fb0-8e5c-4689-8664-8cc78f9ef528"
maturity = "experimental"
