name = "Qiskit Experiments"
url = "https://github.com/qiskit-community/qiskit-experiments"
description = "Run characterizing, calibrating, and benchmarking quantum experiments."
licence = "Apache 2.0"
labels = []
ibm_maintained = true
created_at = 1661785302.25299
updated_at = 1661785302.25299
category = "Other"
reference_paper = "https://doi.org/10.21105/joss.05329"
documentation = "https://qiskit-community.github.io/qiskit-experiments/"
uuid = "6e94a8b7-65a7-4fee-b71e-25191203fa49"

[github]
url = "https://github.com/qiskit-community/qiskit-experiments"
owner = "qiskit-community"
repo = "qiskit-experiments"
stars = 190
homepage = "https://qiskit-community.github.io/qiskit-experiments/"
license = "Apache License 2.0"
description = "Qiskit Experiments"
total_dependent_repositories = 181
total_dependent_packages = 15
last_commit = 2026-04-17T17:14:24Z
last_activity = 2026-04-23T20:13:47Z

[badge]
url = "https://qisk.it/e-6e94a8b7"
style = "flat"

[checks.007]
since = 2026-04-08T16:22:58.930764
details = "the entry `member.interface` does not exist and it is mandatory"
discussion = "https://github.com/Qiskit/ecosystem/issues/1083"
importance = "CRITICAL"

[pypi.qiskit-experiments]
package_name = "qiskit-experiments"
version = "0.13.0"
last_release_date = 2025-11-05T17:16:04
url = "https://pypi.org/project/qiskit-experiments/"
requires_qiskit = ">=1.3"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24T22:41:40Z
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 108106
last_180_days_downloads = 435508
