name = "fast-pauli"
url = "https://github.com/qognitive/fast-pauli"
description = "Conduct efficient multiplication of tensor products of Pauli matrices against a batch of vectors and other mathematical operations."
license = "BSD-2-Clause"
contact_info = "dev@qognitive.io"
affiliations = "Qognitive Inc"
labels = ["HPC", "quantum information"]
interfaces = ["Python", "C++"]
website = "https://qognitive.io"
category = "Application"
reference_paper = "https://arxiv.org/abs/2301.00560"
documentation = "https://qognitive-fast-pauli.readthedocs-hosted.com/en/latest/"
packages = []
uuid = "b4d78374-40eb-4118-bb22-45e97b2dc0c5"
maturity = "production-ready"
status = "Under revision"

[github]
url = "https://github.com/qognitive/fast-pauli"
owner = "qognitive"
repo = "fast-pauli"
stars = 15
homepage = "https://qognitive-fast-pauli.readthedocs-hosted.com/en/latest/"
license = "BSD-2-Clause"
description = "Python/C++ library for optimized operations on Pauli matrices and Pauli strings"
estimated_contributors = 4
total_dependent_repositories = 0
total_dependent_packages = 0
created_at = 2024-06-06
last_commit = 2025-04-09
last_activity = 2026-07-14

[badge]
url = "https://qisk.it/e-b4d78374"
style = "flat"

[pypi.fast-pauli]
package_name = "fast-pauli"
version = "0.0.35"
last_release_date = 2025-04-09
description = "fast pauli"
url = "https://pypi.org/project/fast-pauli/"
status = "active"
maintainers = [
  "https://pypi.org/user/rsamson78/",
  "https://pypi.org/user/vertefra-qcog/",
]
requires_qiskit = ">=0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-07-02
highest_supported_qiskit_version = "2.5.0"
last_month_downloads = 92
last_180_days_downloads = 1602

[checks.G07]
since = 2026-09-17
details = "Last commit was more than 12 months ago. This might be a sign of a project that is not actively maintained. Maybe `member.maturity` should be set as `as-is`"
importance = "STRONG-RECOMMENDATION"

[checks.P10]
since = 2026-07-09
xfailed = "Issue asking for the cap submitted https://github.com/qognitive/fast-pauli/issues/98, waiting for a release with the fix"
xfailed_until = "2027-03-31"
details = "Python package fast-pauli declared itself compatible to a not-yet-released major version of Qiskit"
discussion = "https://github.com/qognitive/fast-pauli/issues/98"
importance = "RECOMMENDATION"

[checks.P12]
since = 2026-07-06
details = "The PyPI package fast-pauli does not have a declared license"
discussion = "https://github.com/qognitive/fast-pauli/issues/97"
importance = "RECOMMENDATION"
