name = "Qiskit Fermions"
submission_number = 1150
url = "https://github.com/Qiskit/qiskit-fermions"
description = "Qiskit with tools for working on fermionic systems."
labels = [ "physics", "high-level synthesis", "quantum information",]
interfaces = [ "C", "Python",]
ibm_maintained = true
category = "Application"
pattern_steps = []
documentation = "https://qiskit.github.io/qiskit-fermions/"
packages = []
uuid = "3794ea8c-64fc-4a23-8c0c-a78366eeb373"
