name = "Qiskit Fermions"
submission_number = 1150
url = "https://github.com/Qiskit/qiskit-fermions"
description = "Tools for working on fermionic systems."
labels = [ "physics", "high-level synthesis", "quantum information",]
interfaces = [ "C", "Python",]
ibm_maintained = true
category = "Application"
pattern_steps = []
documentation = "https://qiskit.github.io/qiskit-fermions/"
packages = []
uuid = "487b5ec4-3ea3-453f-89a4-870341181e73"
