name = "Qiskit Fermions"
submission_number = 1150
url = "https://github.com/Qiskit/qiskit-fermions"
description = "Tools for working on fermionic systems."
labels = [ "physics", "high-level synthesis", "quantum information",]
interfaces = [ "C", "Python",]
ibm_maintained = true
category = "Application"
pattern_steps = []
documentation = "https://qiskit.github.io/qiskit-fermions/"
packages = []
uuid = "487b5ec4-3ea3-453f-89a4-870341181e73"
maturity = "experimental"
status = "Qiskit Project"

[github]
url = "https://github.com/Qiskit/qiskit-fermions"
owner = "Qiskit"
repo = "qiskit-fermions"
stars = 8
homepage = "https://qiskit.github.io/qiskit-fermions/"
license = "Apache License 2.0"
description = "This package extends Qiskit with tools for working on fermionic systems."
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-06-29
last_activity = 2026-06-29

[badge]
url = "https://qisk.it/e-487b5ec4"
style = "flat"
