name = "ffsim"
url = "https://github.com/qiskit-community/ffsim"
description = "ffsim is a software library for simulating fermionic quantum circuits that conserve particle number and the Z component of spin."
license = "Apache License 2.0"
affiliations = "IBM"
labels = [ "chemistry",]
interfaces = [ "Python",]
website = "https://qiskit-community.github.io/ffsim/"
category = "Circuit simulator"
documentation = "https://qiskit-community.github.io/ffsim/"
uuid = "8bbab14b-6cbb-4e09-8040-d5afd359deec"
maturity = "production-ready"

[github]
url = "https://github.com/qiskit-community/ffsim"
owner = "qiskit-community"
repo = "ffsim"
stars = 82
homepage = "https://qiskit-community.github.io/ffsim/"
license = "Apache License 2.0"
description = "Faster simulation of fermionic quantum circuits."
estimated_contributors = 12
total_dependent_repositories = 12
total_dependent_packages = 3
last_commit = 2026-05-06
last_activity = 2026-05-17

[badge]
url = "https://qisk.it/e-8bbab14b"
style = "flat"

[pypi.ffsim]
package_name = "ffsim"
version = "0.0.80"
last_release_date = 2026-05-06
description = "Faster simulation of fermionic quantum circuits."
url = "https://pypi.org/project/ffsim/"
requires_qiskit = ">=1.3"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 19369
last_180_days_downloads = 71988
