name = "ffsim"
url = "https://github.com/qiskit-community/ffsim"
description = "ffsim is a software library for simulating fermionic quantum circuits that conserve particle number and the Z component of spin."
licence = "Apache License 2.0"
affiliations = "IBM"
labels = [ "chemistry",]
website = "https://qiskit-community.github.io/ffsim/"
category = "Circuit simulator"
uuid = "8bbab14b-6cbb-4e09-8040-d5afd359deec"
badge = "https://qisk.it/e-8bbab14b"

[github]
url = "https://github.com/qiskit-community/ffsim"
owner = "qiskit-community"
repo = "ffsim"
stars = 74
homepage = "https://qiskit-community.github.io/ffsim/"
license = "Apache License 2.0"
description = "Faster simulation of fermionic quantum circuits."
estimated_contributors = 12
total_dependent_repositories = 12
total_dependent_packages = 3
last_commit = 2026-04-13T18:50:31Z
last_activity = 2026-04-14T07:37:32Z

[checks.007]
since = 2026-04-08T16:22:49.504226
details = "the entry `member.interface` does not exist and it is mandatory"
importance = "CRITICAL"
discussion = "https://github.com/Qiskit/ecosystem/issues/1083"

[pypi.ffsim]
package_name = "ffsim"
version = "0.0.77"
last_release_date = 2026-03-28T16:13:03
url = "https://pypi.org/project/ffsim/"
requires_qiskit = ">=1.3"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-03-13T02:30:30Z
highest_supported_qiskit_version = "2.3.1"
last_month_downloads = 13235
last_180_days_downloads = 62368
