name = "Qiskit Finance"
url = "https://github.com/qiskit-community/qiskit-finance"
description = "Includes uncertainty components for stock/securities problems, Ising translators for portfolio optimizations, and data providers."
license = "Apache-2.0"
labels = ["finance"]
interfaces = ["Python"]
created_at = 2021-11-08
category = "Application"
documentation = "https://qiskit-community.github.io/qiskit-finance/"
packages = []
uuid = "8ebeec26-5043-4423-9cdc-bfa92bd4ad63"
maturity = "production-ready"

[github]
url = "https://github.com/qiskit-community/qiskit-finance"
owner = "qiskit-community"
repo = "qiskit-finance"
stars = 325
homepage = "https://qiskit-community.github.io/qiskit-finance/"
license = "Apache-2.0"
description = "Quantum Finance"
total_dependent_repositories = 142
total_dependent_packages = 5
last_commit = 2025-12-12
last_activity = 2026-07-02

[badge]
url = "https://qisk.it/e-8ebeec26"
style = "flat"

[checks.P10]
since = 2026-07-09T11:29:53.067305
details = "Python package qiskit-finance declared itself compatible to a not-yet-released major version of Qiskit"
importance = "RECOMMENDATION"

[pypi.qiskit-finance]
package_name = "qiskit-finance"
version = "0.4.1"
last_release_date = 2024-02-29
license = "Apache-2.0"
description = "Qiskit Finance: A library of quantum computing finance experiments"
url = "https://pypi.org/project/qiskit-finance/"
status = "active"
maintainers = ["https://pypi.org/org/qiskit/"]
requires_qiskit = ">=0.45"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 9979
last_180_days_downloads = 61638
