name = "qiskit-fortran"
submission_number = 1172
url = "https://github.com/Qiskit/qiskit-fortran"
description = "Fortran ISO_C_BINDING interface to the Qiskit C API"
labels = []
interfaces = ["Fortran"]
ibm_maintained = true
category = "Language binding"
packages = []
uuid = "07b513bb-798b-42cf-9f81-7f7df48b99c6"
maturity = "experimental"
status = "Qiskit Project"

[github]
url = "https://github.com/Qiskit/qiskit-fortran"
owner = "Qiskit"
repo = "qiskit-fortran"
stars = 3
description = "Fortran binding for Qiskit"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-06-19
last_activity = 2026-06-23

[badge]
url = "https://qisk.it/e-07b513bb"
style = "flat"
