name = "Fulqrum"
submission_number = 1172
url = "https://github.com/qiskit-community/fulqrum"
labels = ["research", "physics"]
interfaces = ["Python"]
category = "Application"
documentation = "https://qiskit-community.github.io/fulqrum/"
packages = []
uuid = "7d6c3172-7bb5-4c5a-b0a3-87aa378ee356"
maturity = "experimental"

[github]
url = "https://github.com/qiskit-community/fulqrum"
owner = "qiskit-community"
repo = "fulqrum"
stars = 12
homepage = "https://qiskit-community.github.io/fulqrum/dev/"
license = "Apache-2.0"
description = "A generalized framework for quantum subspace eigenproblems"
estimated_contributors = 3
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-07-18
last_activity = 2026-07-18

[badge]
url = "https://qisk.it/e-7d6c3172"
style = "flat"
