name = "Fulqrum"
submission_number = 1172
url = "https://github.com/qiskit-community/fulqrum"
labels = ["research", "physics"]
interfaces = ["Python"]
category = "Application"
documentation = "https://qiskit-community.github.io/fulqrum/"
packages = []
uuid = "7d6c3172-7bb5-4c5a-b0a3-87aa378ee356"
maturity = "experimental"
status = "Early Project"

[github]
url = "https://github.com/qiskit-community/fulqrum"
owner = "qiskit-community"
repo = "fulqrum"
stars = 15
homepage = "https://qiskit-community.github.io/fulqrum"
license = "Apache-2.0"
description = "A generalized framework for quantum subspace eigenproblems"
estimated_contributors = 3
total_dependent_repositories = 0
total_dependent_packages = 0
created_at = 2026-03-04
last_commit = 2026-09-17
last_activity = 2026-09-18

[badge]
url = "https://qisk.it/e-7d6c3172"
style = "flat"

[pypi.fulqrum]
package_name = "fulqrum"
version = "0.4.4"
last_release_date = 2026-09-09
url = "https://pypi.org/project/fulqrum/"
status = "active"
maintainers = [
  "https://pypi.org/org/qiskit/",
  "https://pypi.org/user/nonhermitian/",
]
last_month_downloads = 717
last_180_days_downloads = 717

[checks.P12]
since = 2026-09-17
details = "member.pypi.fulqrum does not have a declared license"
discussion = "https://github.com/qiskit-community/fulqrum/pull/122"
importance = "RECOMMENDATION"
