name = "Qiskit Functions Catalog IBM Client"
submission_number = 1342
url = "https://github.com/Qiskit/qiskit-ibm-catalog"
description = "Client for the IBM Quantum Platform's Qiskit Functions service."
labels = ["cloud service"]
interfaces = ["Python"]
ibm_maintained = true
category = "Tooling"
packages = []
uuid = "81dcc42e-55ed-4a74-9bc0-5aaac2505b86"
maturity = "production-ready"

[github]
owner = "Qiskit"
repo = "qiskit-ibm-catalog"

[pypi.qiskit-ibm-catalog]
package_name = "qiskit-ibm-catalog"
