name = "Qiskit Functions Catalog IBM Client"
submission_number = 1342
url = "https://github.com/Qiskit/qiskit-ibm-catalog"
description = "Client for the IBM Quantum Platform's Qiskit Functions service."
labels = ["cloud service"]
interfaces = ["Python"]
ibm_maintained = true
category = "Tooling"
packages = []
uuid = "81dcc42e-55ed-4a74-9bc0-5aaac2505b86"
maturity = "production-ready"

[github]
url = "https://github.com/Qiskit/qiskit-ibm-catalog"
owner = "Qiskit"
repo = "qiskit-ibm-catalog"
stars = 17
license = "Apache-2.0"
description = "Client for the IBM Quantum Platform's Qiskit Functions service"
last_commit = 2026-08-31
last_activity = 2026-08-31

[pypi.qiskit-ibm-catalog]
package_name = "qiskit-ibm-catalog"
version = "0.19.0"
last_release_date = 2026-08-20
url = "https://pypi.org/project/qiskit-ibm-catalog/"
status = "active"
maintainers = ["https://pypi.org/org/qiskit/", "https://pypi.org/user/Tansito/"]
last_month_downloads = 7294
last_180_days_downloads = 41173
