name = "Qiskit Functions Catalog IBM Client"
submission_number = 1342
url = "https://github.com/Qiskit/qiskit-ibm-catalog"
description = "Client for the IBM Quantum Platform's Qiskit Functions service."
labels = ["cloud service"]
interfaces = ["Python"]
ibm_maintained = true
category = "Tooling"
packages = ["https://pypi.org/project/qiskit-ibm-catalog/"]
uuid = "81dcc42e-55ed-4a74-9bc0-5aaac2505b86"
maturity = "production-ready"
