name = "gridsynth"
url = "https://github.com/qiskit-community/rsgridsynth"
description = "High-precision Rust synthesizer decomposing single-qubit Z-rotations into Clifford+T gate sequences."
labels = ["unitary synthesis", "circuit optimization"]
interfaces = ["Rust", "Command-line interface (CLI)"]
ibm_maintained = true
category = "Tooling"
packages = ["https://crates.io/crates/rsgridsynth"]
uuid = "913e330d-200c-4a42-990b-a4e615ac5a96"
maturity = "experimental"

[github]
url = "https://github.com/qiskit-community/rsgridsynth"
owner = "qiskit-community"
repo = "rsgridsynth"
stars = 15
license = "MIT"
description = "high-precision Rust-based synthesizer that decomposes single-qubit Z-axis rotations into Clifford+T gate sequences, using number-th..."
total_dependent_repositories = 21
total_dependent_packages = 3
last_commit = 2026-08-01
last_activity = 2026-08-28

[badge]
url = "https://qisk.it/e-913e330d"
style = "flat"
