name = "Grover controlled-diffuser (CUs)"
url = "https://github.com/albayaty/grover_controlled_diffuser"
description = "The CUs is a new quantum diffusion operator for Grover’s algorithm to search for all solutions for Boolean oracles."
license = "Apache-2.0"
contact_info = "albayaty@pdx.edu"
affiliations = "Department of Electrical and Computer Engineering at Portland State University"
labels = ["circuit optimization", "research", "circuit building"]
interfaces = ["Python"]
category = "Paper artifact"
reference_paper = "https://doi.org/10.21203/rs.3.rs-2997276/v1"
packages = []
uuid = "40b3b309-0dfa-482a-89a6-cbaffd18b7ba"
maturity = "as-is"
status = "Unmaintained"

[github]
url = "https://github.com/albayaty/grover_controlled_diffuser"
owner = "albayaty"
repo = "grover_controlled_diffuser"
stars = 0
license = "Apache-2.0"
description = "Grover controlled-diffuser (CUs) for Grover's algorithm"
total_dependent_repositories = 0
total_dependent_packages = 0
created_at = 2024-08-10
last_commit = 2024-10-20

[badge]
url = "https://qisk.it/e-40b3b309"
style = "flat"

[[python]]
package_name = "grover-controlled-diffuser"
version = "1.1"
license = "Apache-1.1"
description = "Grover controlled-diffuser (CUs)"
requires_python = ">=3.9"
requires_qiskit = ">=1.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-08-13
highest_supported_qiskit_version = "2.5.2"
build_backend = "setuptools.build_meta"
source = ["pyproject.toml", "setup.py", "requirements.txt"]
deferred = ["dependencies"]

[[checks.Q03]]
xfailed = "Check-up was introduced after the project was set as unmaintained."
since = 2026-10-01
details = "The qiskit requirement in the grover-controlled-diffuser manifest in the repository allows a not-yet-released major version of Qiskit"
subtest = "python:grover-controlled-diffuser"
importance = "RECOMMENDATION"

[[checks.G08]]
since = 2026-09-24
details = "Unmaintained project should have an archived GitHub repository"
importance = "NICE-TO-HAVE"

