name = "qiskit-gym"
submission_number = 1346
url = "https://github.com/AI4quantum/qiskit-gym"
description = "A collection of quantum information science problems formulated as reinforcement learning environments."
labels = ["quantum information", "research", "benchmarking"]
interfaces = ["Python"]
category = "Application"
packages = []
uuid = "24856641-7888-4c14-99f2-a448d2acf7f3"
maturity = "experimental"

[github]
owner = "AI4quantum"
repo = "qiskit-gym"
