name = "Hamiltonian-Guided Leverage Embedding"
submission_number = 1388
url = "https://github.com/abhi201191/qiskit-addon-hgle"
description = "Hamiltonian-Guided Leverage Embedding (HGLE): Robust Subspace Compression for VQA (QAOA/VQE) Parameter Estimation"
labels = ["optimization", "GPU"]
interfaces = ["Python"]
category = "Other"
reference_paper = "https://arxiv.org/abs/2606.07814"
documentation = "https://abhi201191.github.io/vqa-hgle/"
packages = []
uuid = "0998746a-f743-4db2-9822-2e0b9a42e77d"
maturity = "experimental"
