name = "Qiskit Installer for Windows"
url = "https://github.com/ket-q/qiskit_windows_installer"
description = "Set up Qiskit and Visual Studio Code (VS Code), with a ready-to-use virtual environment for Jupyter notebooks or Python files."
license = "GNU General Public License (GPL)"
contact_info = "axelpetit@yonsei.ac.kr"
affiliations = ""
labels = []
interfaces = ["Python", "Graphical User Interface (GUI)"]
website = "https://ket-q.github.io/qiskit_windows_installer/"
category = "Other"
packages = []
uuid = "7352f04f-0223-4082-bdd9-9e3e207a35da"
maturity = "production-ready"

[github]
url = "https://github.com/ket-q/qiskit_windows_installer"
owner = "ket-q"
repo = "qiskit_windows_installer"
stars = 0
license = "Other"
description = "Installer for Qiskit on Microsoft Windows platforms."
estimated_contributors = 2
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-05-19
last_activity = 2026-07-04

[badge]
url = "https://qisk.it/e-7352f04f"
style = "flat"

[checks.G09]
since = 2026-07-06T12:46:29.207233
details = "member.github.license not detected"
importance = "RECOMMENDATION"

[checks.O02]
since = 2026-07-06T12:46:29.207233
details = "member.license is not OSI-approved"
importance = "IMPORTANT"
