name = "Qiskit Installer for Windows"
url = "https://github.com/ket-q/qiskit_windows_installer"
description = "Set up Qiskit and Visual Studio Code (VS Code), with a ready-to-use virtual environment for Jupyter notebooks or Python files."
license = "GPL-3.0"
contact_info = "axelpetit@yonsei.ac.kr"
affiliations = ""
labels = []
interfaces = ["Python", "Graphical User Interface (GUI)"]
website = "https://ket-q.github.io/qiskit_windows_installer/"
category = "Other"
packages = []
uuid = "7352f04f-0223-4082-bdd9-9e3e207a35da"
maturity = "production-ready"
status = "Under revision"

[github]
url = "https://github.com/ket-q/qiskit_windows_installer"
owner = "ket-q"
repo = "qiskit_windows_installer"
stars = 0
license = "GPL-3.0"
description = "Installer for Qiskit on Microsoft Windows platforms."
estimated_contributors = 2
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-07-12
last_activity = 2026-07-12

[badge]
url = "https://qisk.it/e-7352f04f"
style = "flat"

[checks.027]
since = 2026-07-23
details = "'str' object has no attribute 'hostname'"
importance = "STRONG-RECOMMENDATION"
