name = "Qiskit IonQ Provider"
url = "https://github.com/qiskit-community/qiskit-ionq"
description = "This project contains a provider that allows access to IonQ ion trap quantum systems."
license = "Apache-2.0"
contact_info = ""
labels = [ "cloud service", "provider",]
interfaces = [ "Python",]
created_at = 2022-12-07
category = "Compute provider"
documentation = "https://qiskit-community.github.io/qiskit-ionq/"
packages = []
uuid = "9dec814e-feb8-49c2-818a-f6a2503d38c5"
maturity = "production-ready"

[github]
url = "https://github.com/qiskit-community/qiskit-ionq"
owner = "qiskit-community"
repo = "qiskit-ionq"
stars = 61
homepage = "https://qiskit-community.github.io/qiskit-ionq/"
license = "Apache-2.0"
description = "Qiskit provider for IonQ backends"
estimated_contributors = 16
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-07-06
last_activity = 2026-07-07

[badge]
url = "https://qisk.it/e-9dec814e"
style = "flat"

[pypi.qiskit-ionq]
package_name = "qiskit-ionq"
version = "1.1.1"
last_release_date = 2025-08-30
license = "Apache-2.0"
description = "Qiskit provider for IonQ backends"
url = "https://pypi.org/project/qiskit-ionq/"
status = "active"
maintainers = [ "https://pypi.org/user/ionq/",]
requires_qiskit = ">=2.0.0"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 72910
last_180_days_downloads = 427627
