name = "Qiskit.jl"
url = "https://github.com/Qiskit/Qiskit.jl/"
contact_info = "garrison@ibm.com"
labels = []
interfaces = [ "Julia",]
ibm_maintained = true
category = "Language binding"
documentation = "https://qiskit.github.io/Qiskit.jl/"
uuid = "50b8eb33-872d-44a4-b8f8-5fafa7712393"
maturity = "production-ready"

[github]
url = "https://github.com/Qiskit/Qiskit.jl"
owner = "Qiskit"
repo = "Qiskit.jl"
stars = 17
homepage = "https://qiskit.github.io/Qiskit.jl/"
license = "Apache License 2.0"
description = "Julia binding for Qiskit"
estimated_contributors = 4
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-04-26T03:15:50Z
last_activity = 2026-04-26T16:53:17Z

[julia]
package_name = "Qiskit"
registry = "General"
version = "0.4.0"
license = "Apache-2.0"
owner = "Qiskit"
homepage = "https://qiskit.github.io/Qiskit.jl/"
release_date = 2026-02-01
uuid = "91d9a17d-f964-4b6c-a3c4-2f4cfdea2c95"
estimated_unique_users = 5

[badge]
url = "https://qisk.it/e-50b8eb33"
style = "flat"
