name = "(Large-scale) Quantum Network Coding"
url = "https://github.com/NagyTamas0122/Large-scale_QuantumNetworkCoding"
description = "Simulate (Large-scale) Quantum Network Coding in Quantum Repeater Network environment."
contact_info = "mikrobi.0122@gmail.com"
labels = ["quantum information"]
interfaces = ["Python"]
category = "Application"
reference_paper = "https://ieeexplore.ieee.org/document/8019800"
packages = [
  "https://github.com/NagyTamas0122/Large-scale_QuantumNetworkCoding/blob/main/docs/requirements.txt",
]
uuid = "67bfc31d-8b98-4c10-8ac2-fba3c59e2732"
maturity = "production-ready"
status = "Under revision"

[github]
url = "https://github.com/NagyTamas0122/Large-scale_QuantumNetworkCoding"
owner = "NagyTamas0122"
repo = "Large-scale_QuantumNetworkCoding"
stars = 0
license = "Apache-2.0"
total_dependent_repositories = 0
total_dependent_packages = 0
created_at = 2025-12-09
last_commit = 2025-12-09
last_activity = 2025-12-09

[badge]
url = "https://qisk.it/e-67bfc31d"
style = "flat"

[[requirements]]
file = "docs/requirements.txt"
requires_qiskit = ">=0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-08-13
highest_supported_qiskit_version = "2.5.2"

[[checks.Q03]]
since = 2026-10-05
details = "The qiskit requirement in docs/requirements.txt allows a not-yet-released major version of Qiskit"
subtest = "requirements:docs/requirements.txt"
importance = "RECOMMENDATION"

[[checks.G06]]
since = 2026-07-14
details = "Last activity was more then 6 months ago, which probably means that the project is not actively maintained and/or used. Maybe `member.maturity` should be set as `as-is`?"
importance = "RECOMMENDATION"

[[checks.G12]]
since = 2026-09-24
details = "Last commit was more than (project_age * 2/3) months ago. This might be a sign of a project with good initial momentum that is decelerating."
importance = "IMPORTANT"
