name = "Qiskit LEAN Verify Game"
submission_number = 1325
url = "https://github.com/RexRowan/Qiskit-LEAN-Verify-Game"
description = "Circuit puzzles built on the Qiskit SDK, checked by LEAN."
contact_info = "titaniumdavinci@gmail.com"
labels = ["demo", "circuit building", "quantum information"]
interfaces = ["Python"]
category = "Game/Educational"
packages = ["https://pypi.org/project/qiskit-lean-verify-game/"]
uuid = "26484722-ff86-4278-9eb6-02e61082dc48"
maturity = "experimental"
