name = "Qiskit LEAN bridge"
submission_number = 1293
url = "https://github.com/RexRowan/Qiskit-LEAN-Bridge"
description = "Bridges Qiskit's StandardEquivalenceLibrary to formally verified proofs in inQWIRE/LeanQuantum."
contact_info = "titaniumdavinci@gmail.com"
labels = ["circuit optimization", "quantum information", "research"]
interfaces = ["Python"]
category = "Tooling"
documentation = "https://github.com/RexRowan/Qiskit-LEAN-Bridge/blob/main/README.md"
packages = []
uuid = "dd050939-b3e1-4392-98fb-e669887caff8"
maturity = "experimental"
