name = "Qiskit LEAN bridge"
submission_number = 1293
url = "https://github.com/RexRowan/Qiskit-LEAN-Bridge"
description = "Bridges Qiskit's StandardEquivalenceLibrary to formally verified proofs in inQWIRE/LeanQuantum."
contact_info = "titaniumdavinci@gmail.com"
labels = ["quantum information", "research"]
interfaces = ["Python"]
category = "Tooling"
packages = []
uuid = "dd050939-b3e1-4392-98fb-e669887caff8"
maturity = "experimental"

[github]
url = "https://github.com/RexRowan/Qiskit-LEAN-Bridge"
owner = "RexRowan"
repo = "Qiskit-LEAN-Bridge"
stars = 0
license = "MIT"
description = "Bridges Qiskit's StandardEquivalenceLibrary to formally verified proofs in inQWIRE/LeanQuantum."
last_commit = 2026-08-11
last_activity = 2026-08-11

[badge]
url = "https://qisk.it/e-dd050939"
style = "flat"
