name = "M3"
url = "https://github.com/Qiskit/qiskit-addon-mthree"
description = "Matrix-free Measurement Mitigation (M3). Reduce the effects of readout errors from noisy quantum hardware."
labels = [ "error mitigation", "utility-scale",]
interfaces = [ "Python",]
ibm_maintained = true
created_at = 1678827878.805163
updated_at = 1678827878.805164
category = "Qiskit addon"
reference_paper = "https://link.aps.org/doi/10.1103/PRXQuantum.2.040326"
documentation = "https://qiskit.github.io/qiskit-addon-mthree"
packages = []
uuid = "875968b2-f9e9-44a9-a5dc-4db9c4805021"
maturity = "experimental"
status = "Qiskit Project"

[github]
url = "https://github.com/Qiskit/qiskit-addon-mthree"
owner = "Qiskit"
repo = "qiskit-addon-mthree"
stars = 52
homepage = "https://qiskit.github.io/qiskit-addon-mthree/"
license = "Apache License 2.0"
description = "Matrix-free Measurement Mitigation"
estimated_contributors = 16
total_dependent_repositories = 122
total_dependent_packages = 12
last_commit = 2025-08-06
last_activity = 2026-06-27

[badge]
url = "https://qisk.it/e-875968b2"
style = "flat"

[pypi.mthree]
package_name = "mthree"
version = "3.0.0"
last_release_date = 2025-03-27
description = "M3: Matrix-free measurement mitigation"
url = "https://pypi.org/project/mthree/"
requires_qiskit = ">=1.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 34297
last_180_days_downloads = 153890
