name = "M3"
url = "https://github.com/Qiskit/qiskit-addon-mthree"
description = "Matrix-free Measurement Mitigation (M3). Reduce the effects of readout errors from noisy quantum hardware."
labels = ["error mitigation", "utility-scale"]
interfaces = ["Python"]
ibm_maintained = true
created_at = 2023-03-14
category = "Qiskit addon"
reference_paper = "https://link.aps.org/doi/10.1103/PRXQuantum.2.040326"
documentation = "https://qiskit.github.io/qiskit-addon-mthree"
packages = []
uuid = "875968b2-f9e9-44a9-a5dc-4db9c4805021"
maturity = "experimental"
status = "Qiskit Project"

[github]
url = "https://github.com/Qiskit/qiskit-addon-mthree"
owner = "Qiskit"
repo = "qiskit-addon-mthree"
stars = 55
homepage = "https://qiskit.github.io/qiskit-addon-mthree/"
license = "Apache-2.0"
description = "Matrix-free Measurement Mitigation"
estimated_contributors = 16
total_dependent_repositories = 123
total_dependent_packages = 12
last_commit = 2026-07-03
last_activity = 2026-07-14

[badge]
url = "https://qisk.it/e-875968b2"
style = "flat"

[pypi.mthree]
package_name = "mthree"
version = "3.0.0"
last_release_date = 2025-03-27
license = "Apache-2.0"
description = "M3: Matrix-free measurement mitigation"
url = "https://pypi.org/project/mthree/"
status = "active"
maintainers = ["https://pypi.org/user/nonhermitian/"]
requires_qiskit = ">=1.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 33262
last_180_days_downloads = 172637

[checks.P10]
since = 2026-07-09
details = "Python package mthree declared itself compatible to a not-yet-released major version of Qiskit"
importance = "RECOMMENDATION"
