name = "Multiproduct Formulas (MPF)"
url = "https://github.com/Qiskit/qiskit-addon-mpf"
description = "Reduce the Trotter error of Hamiltonian dynamics with multi-product formulas (MPF)."
license = "Apache-2.0"
contact_info = "oss@zurich.ibm.com"
labels = [
  "circuit building",
  "physics",
  "utility-scale",
  "Hamiltonian simulation",
]
interfaces = ["Python"]
ibm_maintained = true
created_at = 2025-09-24
category = "Qiskit addon"
documentation = "https://qiskit.github.io/qiskit-addon-mpf/"
packages = []
uuid = "99eb5c40-00ee-439c-971e-e3e2a523c83a"
maturity = "experimental"
status = "Qiskit Project"

[github]
url = "https://github.com/Qiskit/qiskit-addon-mpf"
owner = "Qiskit"
repo = "qiskit-addon-mpf"
stars = 36
homepage = "https://qiskit.github.io/qiskit-addon-mpf/"
license = "Apache-2.0"
description = "Reducing the Trotter error of Hamiltonian dynamics with multi-product formulas"
estimated_contributors = 13
total_dependent_repositories = 6
total_dependent_packages = 0
last_commit = 2026-07-01
last_activity = 2026-07-01

[badge]
url = "https://qisk.it/e-99eb5c40"
style = "flat"

[pypi.qiskit-addon-mpf]
package_name = "qiskit-addon-mpf"
version = "0.3.0"
last_release_date = 2025-03-20
license = "Apache-1.1"
description = "Reducing the Trotter error of Hamiltonian dynamics with multi-product formulas"
url = "https://pypi.org/project/qiskit-addon-mpf/"
status = "active"
maintainers = [
  "https://pypi.org/org/qiskit/",
  "https://pypi.org/user/calebj15/",
  "https://pypi.org/user/mrossinek/",
]
requires_qiskit = "<3,>=1.2"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 5638
last_180_days_downloads = 16231
