name = "MQT Bench"
url = "https://github.com/cda-tum/mqt-bench"
description = "A circuit benchmark suite offering the same algorithms across abstraction levels to evaluate quantum software tools and hardware."
license = "MIT"
contact_info = "quantum.cda@xcit.tum.de"
affiliations = "Technical University of Munich (TUM), Germany"
labels = ["circuit optimization", "research", "benchmarking"]
interfaces = ["Python"]
website = "https://www.cda.cit.tum.de/mqtbench/"
category = "Application"
reference_paper = "https://quantum-journal.org/papers/q-2023-07-20-1062/"
documentation = "https://mqt.readthedocs.io/projects/bench/"
packages = []
uuid = "06f1e81e-e82a-4fc2-88b5-60b532248af1"
maturity = "experimental"

[github]
url = "https://github.com/munich-quantum-toolkit/bench"
owner = "munich-quantum-toolkit"
repo = "bench"
stars = 123
homepage = "https://mqt-bench.app/"
license = "MIT"
description = "MQT Bench - An MQT Tool for Benchmarking Quantum Software Tools"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-07-11
last_activity = 2026-07-16

[badge]
url = "https://qisk.it/e-06f1e81e"
style = "flat"

[pypi."mqt.bench"]
package_name = "mqt-bench"
version = "2.2.3"
last_release_date = 2026-07-07
license = "MIT"
description = "MQT Bench - A MQT tool for Benchmarking Quantum Software Tools"
url = "https://pypi.org/project/mqt.bench/"
development_status = "4 - Beta"
status = "active"
maintainers = ["https://pypi.org/org/munich-quantum-toolkit/"]
requires_qiskit = ">=2.0.0"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 5109
last_180_days_downloads = 21363

[checks.P10]
since = 2026-07-09
details = "Python package mqt-bench declared itself compatible to a not-yet-released major version of Qiskit"
importance = "RECOMMENDATION"
