name = "MQT DDSIM"
url = "https://github.com/cda-tum/mqt-ddsim"
description = "A classical quantum circuit simulator based on decision diagrams developed as part of the Munich Quantum Toolkit (MQT)."
license = "MIT license"
contact_info = "quantum.cda@xcit.tum.de"
affiliations = "Technical University of Munich (TUM), Germany"
labels = [ "research",]
interfaces = [ "Python",]
website = "https://mqt.readthedocs.io"
category = "Circuit simulator"
reference_paper = "https://arxiv.org/abs/2405.17543"
documentation = "https://mqt.readthedocs.io/projects/ddsim"
uuid = "b852a97c-eef8-46aa-a635-9c56a66e6ee0"
maturity = "production-ready"

[github]
url = "https://github.com/munich-quantum-toolkit/ddsim"
owner = "munich-quantum-toolkit"
repo = "ddsim"
stars = 161
homepage = "https://mqt.readthedocs.io/projects/ddsim"
license = "MIT License"
description = "MQT DDSIM - A quantum circuit simulator based on decision diagrams written in C++"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-06-24
last_activity = 2026-06-24

[badge]
url = "https://qisk.it/e-b852a97c"
style = "flat"

[pypi."mqt.ddsim"]
package_name = "mqt-ddsim"
version = "2.3.0"
last_release_date = 2026-05-13
license = "MIT"
description = "A quantum simulator based on decision diagrams written in C++"
url = "https://pypi.org/project/mqt.ddsim/"
development_status = "5 - Production/Stable"
requires_qiskit = ">=1.1"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 2709
last_180_days_downloads = 15396
