name = "MQT Predictor"
url = "https://github.com/cda-tum/mqt-predictor"
description = "Automatically select a suitable quantum device for a circuit and get an optimized compiler for the selected device."
license = "MIT"
contact_info = "quantum.cda@xcit.tum.de"
affiliations = "Technical University of Munich (TUM), Germany"
labels = ["circuit optimization", "research", "AI/LLM"]
interfaces = ["Python"]
category = "Transpiler plugin"
reference_paper = "https://arxiv.org/pdf/2310.06889"
documentation = "https://mqt.readthedocs.io/projects/predictor/"
packages = []
uuid = "9d5e2ef2-cac6-479e-a2f9-8014d54403e4"
maturity = "experimental"

[github]
url = "https://github.com/munich-quantum-toolkit/predictor"
owner = "munich-quantum-toolkit"
repo = "predictor"
stars = 86
license = "MIT"
description = "MQT Predictor - A Tool for Automatic Device Selection with Device-Specific Circuit Compilation for Quantum Computing"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-07-20
last_activity = 2026-07-20

[badge]
url = "https://qisk.it/e-9d5e2ef2"
style = "flat"

[pypi."mqt.predictor"]
package_name = "mqt-predictor"
version = "2.4.0"
last_release_date = 2026-07-13
license = "MIT"
description = "MQT Predictor - A MQT Tool for Automatic Device Selection with Device-Specific Circuit Compilation for Quantum Computing"
url = "https://pypi.org/project/mqt.predictor/"
development_status = "4 - Beta"
status = "active"
maintainers = ["https://pypi.org/org/munich-quantum-toolkit/"]
requires_qiskit = ">=1.3.3"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-07-02
highest_supported_qiskit_version = "2.5.0"
last_month_downloads = 276
last_180_days_downloads = 3019

[checks.P10]
since = 2026-07-14
details = "Python package mqt-predictor declared itself compatible to a not-yet-released major version of Qiskit"
importance = "RECOMMENDATION"
