name = "MQT QECC"
url = "https://github.com/cda-tum/mqt-qecc"
description = "A collection of tools for decoding and synthesizing fault-tolerant quantum circuits."
license = "MIT"
contact_info = "quantum.cda@xcit.tum.de"
affiliations = "Technical University of Munich (TUM), Germany"
labels = ["error correction", "research"]
interfaces = ["Python"]
website = "https://mqt.readthedocs.io"
category = "Other"
documentation = "https://mqt.readthedocs.io/projects/qecc/"
packages = []
uuid = "791d4814-0ced-4f5a-94c5-908ceb4b5a90"
maturity = "production-ready"

[github]
url = "https://github.com/munich-quantum-toolkit/qecc"
owner = "munich-quantum-toolkit"
repo = "qecc"
stars = 223
homepage = "https://mqt.readthedocs.io/projects/qecc"
license = "MIT"
description = "MQT QECC - Tools for Quantum Error Correcting Codes"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-07-07
last_activity = 2026-07-07

[badge]
url = "https://qisk.it/e-791d4814"
style = "flat"

[pypi."mqt.qcec"]
package_name = "mqt-qcec"
version = "3.6.1"
last_release_date = 2026-05-20
license = "MIT"
description = "A tool for Quantum Circuit Equivalence Checking"
url = "https://pypi.org/project/mqt.qcec/"
development_status = "5 - Production/Stable"
status = "active"
maintainers = ["https://pypi.org/org/munich-quantum-toolkit/"]
requires_qiskit = ">=1.0.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 10140
last_180_days_downloads = 51408
