name = "MQT QCEC"
url = "https://github.com/cda-tum/mqt-qcec"
description = "A tool for quantum circuit equivalence checking developed as part of the Munich Quantum Toolkit (MQT)."
licence = "MIT license"
contact_info = "quantum.cda@xcit.tum.de"
affiliations = "Technical University of Munich (TUM), Germany"
labels = [ "research", "quantum information",]
website = "https://mqt.readthedocs.io"
category = "Other"
reference_paper = "https://arxiv.org/abs/2405.17543"
documentation = "https://mqt.readthedocs.io/projects/qcec"
uuid = "79415931-2d24-4959-ab15-29dfaeb139b4"
maturity = "production-ready"

[github]
url = "https://github.com/munich-quantum-toolkit/qcec"
owner = "munich-quantum-toolkit"
repo = "qcec"
stars = 111
homepage = "https://mqt.readthedocs.io/projects/qcec"
license = "MIT License"
description = "MQT QCEC - A tool for Quantum Circuit Equivalence Checking"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-05-13T19:11:28Z
last_activity = 2026-05-13T19:11:28Z

[badge]
url = "https://qisk.it/e-79415931"
style = "flat"

[checks.007]
since = 2026-04-08T16:22:59.928875
details = "the entry `member.interfaces` does not exist and it is mandatory"
discussion = "https://github.com/Qiskit/ecosystem/issues/1083"
importance = "IMPORTANT"

[pypi."mqt.qcec"]
package_name = "mqt-qcec"
version = "3.6.0"
last_release_date = 2026-02-02T17:44:07
license = "MIT"
url = "https://pypi.org/project/mqt.qcec/"
requires_qiskit = ">=1.0.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24T22:41:40Z
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 5604
last_180_days_downloads = 49257
