name = "MQT QECC"
url = "https://github.com/cda-tum/mqt-qecc"
description = "A collection of tools for decoding and synthesizing fault-tolerant quantum circuits."
licence = "MIT license"
contact_info = "quantum.cda@xcit.tum.de"
affiliations = "Technical University of Munich (TUM), Germany"
labels = [ "error correction",]
website = "https://mqt.readthedocs.io"
category = "Other"
documentation = "https://mqt.readthedocs.io/projects/qecc/en/latest/"
uuid = "791d4814-0ced-4f5a-94c5-908ceb4b5a90"
maturity = "production-ready"

[github]
url = "https://github.com/munich-quantum-toolkit/qecc"
owner = "munich-quantum-toolkit"
repo = "qecc"
stars = 206
homepage = "https://mqt.readthedocs.io/projects/qecc"
license = "MIT License"
description = "MQT QECC - Tools for Quantum Error Correcting Codes"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-04-25T02:00:57Z
last_activity = 2026-04-25T02:00:57Z

[badge]
url = "https://qisk.it/e-791d4814"
style = "flat"

[checks.007]
since = 2026-04-08T16:22:45.694636
details = "the entry `member.interface` does not exist and it is mandatory"
discussion = "https://github.com/Qiskit/ecosystem/issues/1083"
importance = "IMPORTANT"

[pypi."mqt.qcec"]
package_name = "mqt-qcec"
version = "3.5.0"
last_release_date = 2026-02-02T17:44:07
license = "MIT"
url = "https://pypi.org/project/mqt.qcec/"
requires_qiskit = ">=1.0.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24T22:41:40Z
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 7561
last_180_days_downloads = 50373
