name = "MQT QAO"
url = "https://github.com/cda-tum/mqt-qao"
license = "MIT license"
uuid = "6d4c69e4-1e47-486c-b00f-8a60ae5e01d4"
maturity = "unmaintained"
status = "Alumni"

[github]
url = "https://github.com/cda-tum/mqt-qao"
owner = "cda-tum"
repo = "mqt-qao"

[badge]
url = "https://qisk.it/e-6d4c69e4"
style = "flat"

[pypi."mqt.qao"]
package_name = "mqt-qao"
url = "https://pypi.org/project/mqt.qao/"
