name = "qiskit-noise-learning"
url = "https://github.com/Qiskit/qiskit-noise-learning"
description = "Toolkit for randomization-based characterization of quantum noise, such as layer noise learning."
labels = ["error mitigation", "benchmarking"]
interfaces = ["Python"]
ibm_maintained = true
category = "Tooling"
packages = []
uuid = "25fea67d-3f93-4252-bc51-33c3b20c2331"
maturity = "experimental"
status = "Qiskit Project"

[github]
url = "https://github.com/Qiskit/qiskit-noise-learning"
owner = "Qiskit"
repo = "qiskit-noise-learning"
stars = 8
license = "Apache-2.0"
description = "A toolkit for randomization-based quantum noise characterization."
last_commit = 2026-09-04
last_activity = 2026-09-04

[badge]
url = "https://qisk.it/e-25fea67d"
style = "flat"
