name = "Noisy Quantum Gates"
url = "https://github.com/CERN-IT-INNOVATION/quantum-gates"
description = "Provider with a novel approach for simulating quantum circuits with a realistic noise integrated into gates and modular design."
license = "MIT"
contact_info = "roman.wixinger@gmail.com PAOLO.DAROLD@studenti.units.it michele.grossi@cern.ch vischimichele@gmail.com dibartolomeo.giov@gmail.com"
affiliations = "- CERN Quantum Technology Initiative (https://quantum.cern/our-governance) - University of Trieste, Quantum Mechanics group (https://www.qmts.it)"
labels = ["provider", "research"]
interfaces = ["Python"]
category = "Circuit simulator"
reference_paper = "https://journals.aps.org/prresearch/abstract/10.1103/PhysRevResearch.5.043210"
documentation = "https://quantum-gates.readthedocs.io/en/latest/index.html"
packages = []
uuid = "dd5d5bad-1523-4f3e-aff2-7d474b53d27a"
maturity = "production-ready"

[github]
url = "https://github.com/CERN-QTI/quantum-gates"
owner = "CERN-QTI"
repo = "quantum-gates"
stars = 21
homepage = "https://quantum-gates.readthedocs.io/en/latest/"
license = "MIT"
description = "Noisy Quantum Gates model for simulating the noise of quantum devices."
estimated_contributors = 8
total_dependent_repositories = 3
total_dependent_packages = 0
last_commit = 2026-06-12
last_activity = 2026-06-12

[badge]
url = "https://qisk.it/e-dd5d5bad"
style = "flat"

[checks.P10]
since = 2026-07-09T11:29:53.067305
details = "Python package quantum-gates declared itself compatible to a not-yet-released major version of Qiskit"
importance = "RECOMMENDATION"

[pypi.quantum-gates]
package_name = "quantum-gates"
version = "2.4.0"
last_release_date = 2026-05-02
license = "MIT"
description = "Quantum Noisy Gates Simulation with Python"
url = "https://pypi.org/project/quantum-gates/"
status = "active"
maintainers = ["https://pypi.org/user/roman.wixinger/"]
requires_qiskit = ">=2.0"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 267
last_180_days_downloads = 851
