name = "Qiskit Omelyan"
submission_number = 1202
url = "https://github.com/MarkoMalezic/qiskit-omelyan"
description = "Omelyan-type symmetric product formulas for PauliEvolutionGate synthesis in Qiskit"
contact_info = "malezic15@gmail.com"
labels = [ "high-level synthesis",]
interfaces = [ "Python",]
category = "Transpiler plugin"
pattern_steps = [ "Map",]
reference_paper = "https://arxiv.org/abs/2601.18756"
packages = []
uuid = "9d474247-5c15-481c-afb2-cc58ae884459"
maturity = "bugfixing only"

[github]
url = "https://github.com/MarkoMalezic/qiskit-omelyan"
owner = "MarkoMalezic"
repo = "qiskit-omelyan"
stars = 1
license = "Apache License 2.0"
last_commit = 2026-06-29
last_activity = 2026-06-29

[pypi.qiskit-omelyan]
package_name = "qiskit-omelyan"
version = "0.2.1"
last_release_date = 2026-06-26
description = "Omelyan-based product formulas for time evolution in Qiskit"
url = "https://pypi.org/project/qiskit-omelyan/"
requires_qiskit = ">=2.0.0"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-06-14
highest_supported_qiskit_version = "2.4.2"
last_month_downloads = 249
last_180_days_downloads = 397
