name = "qiskit-addon-opt-mapper"
url = "https://github.com/Qiskit/qiskit-addon-opt-mapper"
description = "Mapping combinatorial optimization problems to quantum computers"
licence = "Apache License 2.0"
labels = []
interfaces = [ "Python",]
ibm_maintained = true
category = "Qiskit addon"
documentation = "https://qiskit.github.io/qiskit-addon-opt-mapper/"
uuid = "ef4e120a-f308-4462-86b6-10e7c7ba17c7"
maturity = "experimental"
status = "Qiskit Project"

[github]
url = "https://github.com/Qiskit/qiskit-addon-opt-mapper"
owner = "Qiskit"
repo = "qiskit-addon-opt-mapper"
stars = 14
homepage = "https://qiskit.github.io/qiskit-addon-opt-mapper/"
license = "Apache License 2.0"
description = "Mapping combinatorial optimization problems to quantum computers"
estimated_contributors = 23
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-05-11
last_activity = 2026-05-21

[badge]
url = "https://qisk.it/e-ef4e120a"
style = "flat"

[pypi.qiskit-addon-opt-mapper]
package_name = "qiskit-addon-opt-mapper"
version = "0.1.0"
last_release_date = 2025-11-03
license = "Apache-2.0"
description = "An addon for optimization problem modeling, providing various utilities and enhancements."
url = "https://pypi.org/project/qiskit-addon-opt-mapper/"
requires_qiskit = "<3"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 1030
last_180_days_downloads = 4154
