name = "Paulice"
submission_number = 1172
url = "https://github.com/Qiskit/qiskit-paulice"
labels = ["utility-scale"]
interfaces = ["Python"]
ibm_maintained = true
category = "Qiskit addon"
pattern_steps = ["Optimize"]
documentation = "https://qiskit.github.io/qiskit-paulice/"
packages = []
uuid = "3309662b-d49a-4636-a6e8-254c4b5f7873"
maturity = "experimental"
status = "Qiskit Project"

[github]
url = "https://github.com/Qiskit/qiskit-paulice"
owner = "Qiskit"
repo = "qiskit-paulice"
stars = 10
homepage = "https://quantum.cloud.ibm.com/docs/en/addons/qiskit-addon-paulice"
license = "Apache-2.0"
description = "Embedding spacetime Pauli checks into Clifford circuits"
estimated_contributors = 3
total_dependent_repositories = 0
total_dependent_packages = 1
last_commit = 2026-06-30
last_activity = 2026-07-01

[badge]
url = "https://qisk.it/e-3309662b"
style = "flat"

[pypi.qiskit-paulice]
package_name = "qiskit-paulice"
version = "0.2.1"
last_release_date = 2026-05-26
license = "Apache-1.1"
description = "A library for implementing spacetime coherent Pauli checks"
url = "https://pypi.org/project/qiskit-paulice/"
status = "active"
maintainers = ["https://pypi.org/org/qiskit/"]
requires_qiskit = "<3,>=2.1.2"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 1010
last_180_days_downloads = 1299
