name = "Pennylane-Qiskit"
url = "https://github.com/PennyLaneAI/pennylane-qiskit"
description = "The PennyLane-Qiskit plugin integrates the Qiskit quantum computing framework with PennyLane's quantum machine learning capabilities."
licence = "Apache 2.0"
labels = []
created_at = 1678827878.782751
updated_at = 1678827878.782752
category = "Converter"
uuid = "cfbecefc-6cf7-49a6-99c5-049dae76fdcc"
maturity = "production-ready"

[github]
url = "https://github.com/PennyLaneAI/pennylane-qiskit"
owner = "PennyLaneAI"
repo = "pennylane-qiskit"
stars = 230
homepage = "https://docs.pennylane.ai/projects/qiskit"
license = "Apache License 2.0"
description = "The PennyLane-Qiskit plugin integrates the Qiskit quantum computing framework and IBM Q with PennyLane."
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-04-25T06:18:22Z
last_activity = 2026-04-25T06:25:10Z

[badge]
url = "https://qisk.it/e-cfbecefc"
style = "flat"

[checks.007]
since = 2026-04-08T16:22:52.999175
details = "the entry `member.interface` does not exist and it is mandatory"
discussion = "https://github.com/Qiskit/ecosystem/issues/1083"
importance = "IMPORTANT"

[checks.PQ1]
since = 2026-04-30T11:32:49.789583
details = "assert False"
importance = "CRITICAL"

[pypi.pennylane-qiskit]
package_name = "pennylane-qiskit"
version = "0.44.1"
last_release_date = 2026-01-22T22:16:30
url = "https://pypi.org/project/PennyLane-qiskit/"
requires_qiskit = "<2.2,>=2.0"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2025-08-19T15:29:40Z
highest_supported_qiskit_version = "2.1.2"
last_month_downloads = 20717
last_180_days_downloads = 130508
