name = "piQture"
url = "https://github.com/SaashaJoshi/piQture"
description = "Develop, execute, and train Quantum Machine Learning models tailored for image processing tasks. Seamlessly integrated with Qiskit."
license = "Apache-2.0"
contact_info = "saashajoshi08@gmail.com"
affiliations = "University of Victoria"
labels = ["QML"]
interfaces = ["Python"]
category = "Application"
reference_paper = "https://hdl.handle.net/1828/16627"
documentation = "https://saashajoshi.github.io/piQture/"
packages = []
uuid = "da29aca4-ba28-4d62-942b-f4c5371e7b6e"
maturity = "production-ready"

[github]
url = "https://github.com/SaashaJoshi/piQture"
owner = "SaashaJoshi"
repo = "piQture"
stars = 60
homepage = "https://saashajoshi.github.io/piQture/"
license = "Apache-2.0"
description = "piQture: A quantum machine learning library for image processing."
estimated_contributors = 10
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-11-20
last_activity = 2026-06-14

[badge]
url = "https://qisk.it/e-da29aca4"
style = "flat"

[pypi.piqture]
package_name = "piqture"
version = "0.2.0"
last_release_date = 2025-07-25
license = "Apache-2.0"
description = "piQture: A QML library for Image Processing"
url = "https://pypi.org/project/piQture/"
status = "active"
maintainers = ["https://pypi.org/user/SaashaJoshi/"]
requires_qiskit = ">=2.0.0"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 36
last_180_days_downloads = 218

[checks.P10]
since = 2026-07-09
details = "Python package piqture declared itself compatible to a not-yet-released major version of Qiskit"
importance = "RECOMMENDATION"
