name = "Propagated Noise Absorption (PNA)"
url = "https://github.com/Qiskit/qiskit-addon-pna"
description = "Mitigate gate noise in expectation values by propagating the observable through the inverse noise channel."
labels = [ "utility-scale",]
interfaces = [ "Python",]
ibm_maintained = true
category = "Qiskit addon"
pattern_steps = [ "Post-process",]
documentation = "https://qiskit.github.io/qiskit-addon-pna/"
packages = []
uuid = "4cb3b182-7484-445f-897b-ded8e295d755"
maturity = "experimental"
status = "Qiskit Project"

[github]
url = "https://github.com/Qiskit/qiskit-addon-pna"
owner = "Qiskit"
repo = "qiskit-addon-pna"
stars = 8
homepage = "https://qiskit.github.io/qiskit-addon-pna/"
license = "Apache License 2.0"
description = "Mitigate gate noise in expectation values by propagating the observable through the inverse noise channel."
estimated_contributors = 9
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-07-03
last_activity = 2026-07-03

[badge]
url = "https://qisk.it/e-4cb3b182"
style = "flat"

[pypi.qiskit-addon-pna]
package_name = "qiskit-addon-pna"
version = "0.2.0"
last_release_date = 2025-11-13
license = "Apache Software License"
description = "Mitigate a global noise channel by propagating an observable through the anti-noise."
url = "https://pypi.org/project/qiskit-addon-pna/"
status = "active"
maintainers = [ "https://pypi.org/org/qiskit/",]
requires_qiskit = "<3,>=2.1.2"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 624
last_180_days_downloads = 990
