name = "POVM Toolbox"
url = "https://github.com/qiskit-community/povm-toolbox"
description = "A toolbox for the implementation of positive operator-valued measures (POVMs)."
license = "Apache-2.0"
contact_info = "oss@zurich.ibm.com"
labels = ["circuit building", "quantum information"]
interfaces = ["Python"]
category = "Other"
documentation = "https://qiskit-community.github.io/povm-toolbox/"
packages = []
uuid = "1fb3d426-e458-4c7a-be9e-e31a758bb872"
maturity = "production-ready"

[github]
url = "https://github.com/qiskit-community/povm-toolbox"
owner = "qiskit-community"
repo = "povm-toolbox"
stars = 42
homepage = "https://qiskit-community.github.io/povm-toolbox/"
license = "Apache-2.0"
description = "A toolbox for the implementation of positive operator-valued measures (POVMs)."
estimated_contributors = 6
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-06-22
last_activity = 2026-06-22

[badge]
url = "https://qisk.it/e-1fb3d426"
style = "flat"

[pypi.povm-toolbox]
package_name = "povm-toolbox"
version = "0.2.0"
last_release_date = 2025-06-26
license = "Apache-2.0"
description = "A toolbox for the implementation of positive operator-valued measures (POVMs)."
url = "https://pypi.org/project/povm-toolbox/"
status = "active"
maintainers = [
  "https://pypi.org/org/qiskit/",
  "https://pypi.org/user/mrossinek/",
  "https://pypi.org/user/timmintam/",
]
requires_qiskit = "<3,>=1.4"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 205
last_180_days_downloads = 2850
