name = "POVM Toolbox"
url = "https://github.com/qiskit-community/povm-toolbox"
description = "A toolbox for the implementation of positive operator-valued measures (POVMs)."
licence = "Apache License 2.0"
contact_info = "oss@zurich.ibm.com"
labels = [ "circuit building",]
category = "Other"
documentation = "https://qiskit-community.github.io/povm-toolbox/"
uuid = "1fb3d426-e458-4c7a-be9e-e31a758bb872"
maturity = "production-ready"

[github]
url = "https://github.com/qiskit-community/povm-toolbox"
owner = "qiskit-community"
repo = "povm-toolbox"
stars = 41
homepage = "https://qiskit-community.github.io/povm-toolbox/"
license = "Apache License 2.0"
description = "A toolbox for the implementation of positive operator-valued measures (POVMs)."
estimated_contributors = 6
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-04-14T07:58:51Z
last_activity = 2026-04-23T03:23:06Z

[badge]
url = "https://qisk.it/e-1fb3d426"
style = "flat"

[checks.007]
since = 2026-04-08T16:22:52.017483
details = "the entry `member.interfaces` does not exist and it is mandatory"
discussion = "https://github.com/Qiskit/ecosystem/issues/1083"
importance = "IMPORTANT"

[pypi.povm-toolbox]
package_name = "povm-toolbox"
version = "0.2.0"
last_release_date = 2025-06-26T08:05:07
license = "Apache-2.0"
url = "https://pypi.org/project/povm-toolbox/"
requires_qiskit = "<3,>=1.4"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24T22:41:40Z
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 222
last_180_days_downloads = 2679
