name = "psf-zero-qiskit"
submission_number = 1058
url = "https://github.com/love-os-architect/psf-zero"
description = "Geometric quantum-control extension for Qiskit. Achieves zero-friction phase sync via projective regularization to eliminate noise."
contact_info = "love.os.architect@proton.me"
labels = [ "error mitigation", "optimization",]
interface = [ "Python",]
category = "Transpiler plugin"
documentation = "https://github.com/love-os-architect/README/blob/main/LOVE_OS_WHITE_PAPER_V1.md"
packages = []
uuid = "ec4cc7b4-0953-4a29-bea9-d9abeeddc16a"

[github]
url = "https://github.com/love-os-architect/psf-zero"
owner = "love-os-architect"
repo = "psf-zero"
stars = 2
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-04-21T10:25:38Z
last_activity = 2026-04-21T10:25:39Z

[badge]
url = "https://qisk.it/e-ec4cc7b4"
style = "flat"
