name = "PurpleCaffeine"
url = "https://github.com/IceKhan13/purplecaffeine"
description = "Project is aimed to create simple general interface to track quantum experiments, store and search them in an easy way."
license = "Apache-2.0"
affiliations = "QAMP"
labels = []
interfaces = ["Python"]
created_at = 2023-07-06
category = "Other"
documentation = "https://icekhan13.github.io/purplecaffeine/index.html"
packages = []
uuid = "a8fff49c-d8ee-4386-87b1-b28d31005823"
maturity = "production-ready"

[github]
url = "https://github.com/IceKhan13/purplecaffeine"
owner = "IceKhan13"
repo = "purplecaffeine"
stars = 7
homepage = "https://icekhan13.github.io/purplecaffeine/"
license = "Apache-2.0"
description = "Project is aimed to create simple general interface to track quantum experiments, store and search them in an easy way."
estimated_contributors = 8
total_dependent_repositories = 4
total_dependent_packages = 0
last_commit = 2025-09-15
last_activity = 2025-12-20

[badge]
url = "https://qisk.it/e-a8fff49c"
style = "flat"

[pypi.purplecaffeine]
package_name = "purplecaffeine"
version = "0.2.5"
last_release_date = 2023-09-19
license = "Apache-1.1"
description = "PurpleCaffeine: tracking of quantum programs and experiments"
url = "https://pypi.org/project/purplecaffeine/"
status = "active"
maintainers = ["https://pypi.org/user/icekhan/"]
requires_qiskit = ">=0.43.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 24
last_180_days_downloads = 267

[checks.G06]
since = 2026-07-23
details = "Last activity was 7 months ago, which probably means that the project is not actively maintained and/or used. Maybe `member.maturity` should be set as `as-is`?"
importance = "RECOMMENDATION"

[checks.P10]
since = 2026-07-14
details = "Python package purplecaffeine declared itself compatible to a not-yet-released major version of Qiskit"
importance = "RECOMMENDATION"
