name = "PyEncode"
submission_number = 1397
url = "https://github.com/UW-ERSL/PyEncode"
description = "An open-source Python library for structured quantum state preparation with O(polylog(m)) gates"
contact_info = "ksuresh@wisc.edu"
labels = ["circuit building", "high-level synthesis", "research", "tensor networks"]
interfaces = ["Python"]
category = "Transpiler plugin"
reference_paper = "https://arxiv.org/abs/2603.28259"
packages = ["https://github.com/UW-ERSL/PyEncode/blob/main/setup.py"]
uuid = "d31f20d9-ca23-4c27-a3bb-2bd37327e2b9"
maturity = "production-ready"
