name = "Qamomile"
url = "https://github.com/Jij-Inc/Qamomile"
description = "Model constrained optimization problems using an algebraic modeler and convert them for quantum optimization algorithms."
licence = "Apache License 2.0"
contact_info = "h.matsuyama@j-ij.com"
affiliations = "Jij Inc."
labels = [ "optimization",]
category = "SDK"
documentation = "https://jij-inc.github.io/Qamomile/"
uuid = "50cd2126-dc2c-45f8-b3e7-fb1d132f7d02"
maturity = "production-ready"

[github]
url = "https://github.com/Jij-Inc/Qamomile"
owner = "Jij-Inc"
repo = "Qamomile"
stars = 16
license = "Apache License 2.0"
estimated_contributors = 15
total_dependent_repositories = 2
total_dependent_packages = 1
last_commit = 2026-04-26T15:28:58Z
last_activity = 2026-04-26T15:28:59Z

[badge]
url = "https://qisk.it/e-50cd2126"
style = "flat"

[checks.007]
since = 2026-04-08T16:23:03.521067
details = "the entry `member.interfaces` does not exist and it is mandatory"
discussion = "https://github.com/Qiskit/ecosystem/issues/1083"
importance = "IMPORTANT"

[pypi.qamomile]
package_name = "qamomile"
version = "0.11.1"
last_release_date = 2026-03-27T11:22:34
url = "https://pypi.org/project/qamomile/"
requires_qiskit = "<3.0.0,>=2.1.0"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24T22:41:40Z
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 781
last_180_days_downloads = 4340
