name = "Qamposer"
submission_number = 1334
url = "https://github.com/QAMP-62/qamposer-react"
description = "Modular Quantum Composer that can be integrated into your applications, including games and educational tools."
contact_info = "qvuaalnlteuym@gmail.com"
labels = ["circuit building", "openqasm"]
interfaces = ["Web interface", "Other language"]
website = "https://qamposer.org"
category = "Game/Educational"
documentation = "https://qamposer.org/getting-started"
packages = ["https://www.npmjs.com/package/@qamposer/react"]
uuid = "ebaeb5c2-37ce-4827-9acb-b77495e18167"
maturity = "experimental"

[github]
url = "https://github.com/QAMP-62/qamposer-react"
owner = "QAMP-62"
repo = "qamposer-react"
stars = 4
homepage = "https://qamposer.org/"
license = "Apache-2.0"
description = "Modular Quantum Composer that can be integrated into your applications, including games and educational tools."
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-09-04
