name = "Qamposer"
submission_number = 1334
url = "https://github.com/QAMP-62/qamposer-react"
description = "Modular Quantum Composer that can be integrated into your applications, including games and educational tools."
contact_info = "qvuaalnlteuym@gmail.com"
labels = ["circuit building", "openqasm"]
interfaces = ["Web interface", "Other language"]
website = "https://qamposer.org"
category = "Game/Educational"
documentation = "https://qamposer.org/getting-started"
packages = ["https://www.npmjs.com/package/@qamposer/react"]
uuid = "ebaeb5c2-37ce-4827-9acb-b77495e18167"
maturity = "experimental"
