name = "QASM Runner for IBM platforms"
url = "https://github.com/TownsendBrown/QASM-Runner-Qiskit-Platform"
description = "A command-line tool for executing OpenQASM 2.0 files on IBM Quantum hardware and simulators."
contact_info = "stiofancondon@outlook.com"
labels = [ "openqasm",]
category = "Converter"
pattern_steps = [ "Execute",]
uuid = "5b05d5a3-26c6-4487-91cc-3ca3aeaf0d6b"
maturity = "production-ready"

[github]
url = "https://github.com/TownsendBrown/QASM-Runner-for-IBM-platforms"
owner = "TownsendBrown"
repo = "QASM-Runner-for-IBM-platforms"
stars = 0
license = "MIT License"
description = "A command-line tool for executing OpenQASM 2.0 files on IBM Quantum hardware and simulators."
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-11-13T21:48:08Z
last_activity = 2025-11-13T21:48:09Z

[badge]
url = "https://qisk.it/e-5b05d5a3"
style = "flat"

[checks.007]
since = 2026-04-08T16:22:53.827705
details = "the entry `member.interfaces` does not exist and it is mandatory"
importance = "IMPORTANT"
