name = "QASM Runner for IBM platforms"
url = "https://github.com/TownsendBrown/QASM-Runner-Qiskit-Platform"
description = "A command-line tool for executing OpenQASM 2.0 files on IBM Quantum hardware and simulators."
contact_info = "stiofancondon@outlook.com"
labels = ["openqasm"]
interfaces = ["Python", "Command-line interface (CLI)"]
category = "Converter"
pattern_steps = ["Execute"]
packages = []
uuid = "5b05d5a3-26c6-4487-91cc-3ca3aeaf0d6b"
maturity = "production-ready"

[github]
url = "https://github.com/TownsendBrown/QASM-Runner-for-IBM-platforms"
owner = "TownsendBrown"
repo = "QASM-Runner-for-IBM-platforms"
stars = 0
license = "MIT"
description = "A command-line tool for executing OpenQASM 2.0 files on IBM Quantum hardware and simulators."
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-11-13
last_activity = 2025-11-13

[badge]
url = "https://qisk.it/e-5b05d5a3"
style = "flat"

[checks.G06]
since = 2026-06-14
details = "Last activity was 8 months ago, which is more than 6 months ago. Please update the GitHub repository or set member.maturity to `as-is`."
importance = "RECOMMENDATION"
