name = "qBalance"
submission_number = 1132
url = "https://github.com/neuralsorcerer/qbalance"
description = "A workflow toolkit for balancing quantum compilation, suppression, and mitigation choices over a dataset of quantum circuits."
labels = []
interfaces = [ "Python",]
category = "Application"
pattern_steps = []
reference_paper = "https://arxiv.org/abs/2605.02966"
packages = []
uuid = "3907a817-2a1a-49c2-b65b-64dbee8dfe05"
