name = "qBalance"
submission_number = 1132
url = "https://github.com/neuralsorcerer/qbalance"
description = "A workflow toolkit for balancing quantum compilation, suppression, and mitigation choices over a dataset of quantum circuits."
labels = [ "error mitigation", "circuit optimization",]
interfaces = [ "Python",]
category = "Tooling"
pattern_steps = []
reference_paper = "https://arxiv.org/abs/2605.02966"
packages = []
uuid = "88affdcb-ea75-47ad-956a-bd24f7af1f20"

[github]
owner = "neuralsorcerer"
repo = "qbalance"

[pypi.qbalance]
package_name = "qbalance"
