name = "qb-compiler"
submission_number = 1044
url = "https://github.com/mwpwalshe/qb-compiler"
description = "Calibration-aware quantum circuit compiler. Uses today's hardware noise data for smarter qubit mapping and routing."
contact_info = "michael.walshe@qubitboost.io"
labels = [ "circuit optimization", "error mitigation",]
interface = [ "Python",]
website = "https://qubitboost.io/compiler"
category = "Transpiler plugin"
documentation = "https://mwpwalshe.github.io/qb-compiler/"
packages = []
uuid = "2334d2a1-93bc-4652-8e15-ac395b2d3dd9"

[github]
url = "https://github.com/mwpwalshe/qb-compiler"
owner = "mwpwalshe"
repo = "qb-compiler"
stars = 0
homepage = "https://qubitboost.io/compiler"
license = "Apache License 2.0"
description = "Quantum execution intelligence toolkit for circuit preflight checks, backend analysis, calibration-aware compilation, and hardware-..."
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-04-23T18:53:24Z
last_activity = 2026-04-23T18:54:05Z

[badge]
url = "https://qisk.it/e-2334d2a1"
style = "flat"

[pypi.qb-compiler]
package_name = "qb-compiler"
version = "0.3.0"
last_release_date = 2026-03-14T16:16:04
license = "Apache-2.0"
url = "https://pypi.org/project/qb-compiler/"
requires_qiskit = "<2.0,>=1.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = false
highest_supported_qiskit_release_date = 2025-10-13T14:23:38Z
highest_supported_qiskit_version = "1.4.5"
last_month_downloads = 231
last_180_days_downloads = 918
