name = "QELM"
url = "https://github.com/R-D-BioTech-Alaska/Qelm"
description = "A quantum-powered NLP project. Creates ultra-compact, efficient LLMs that run instantly on small devices without data centers."
contact_info = "contact@rdbiotechalaska.com"
affiliations = "R&D BioTech Alaska"
labels = ["QML", "circuit building", "research", "AI/LLM"]
interfaces = ["Python"]
category = "Application"
reference_paper = "https://doi.org/10.13140/RG.2.2.11844.90243"
documentation = "https://github.com/R-D-BioTech-Alaska/Qelm/tree/main/Documentation"
packages = []
uuid = "8b3685bb-451f-4d3d-abac-61a5ce48708f"
maturity = "production-ready"
status = "Alumni"

[github]
url = "https://github.com/R-D-BioTech-Alaska/Qelm"
owner = "R-D-BioTech-Alaska"
repo = "Qelm"

[badge]
url = "https://qisk.it/e-8b3685bb"
style = "flat"

[pypi.qelm]
package_name = "qelm"

[checks.001]
since = 2026-07-30
source = "https://github.com/Qiskit/ecosystem/issues/1381"
