name = "qiskit-addon-opt-mapper"
url = "https://github.com/Qiskit/qiskit-addon-opt-mapper"
description = "Mapping combinatorial optimization problems to quantum computers"
licence = "Apache License 2.0"
contact_info = "garrison@ibm.com"
labels = []
ibm_maintained = true
category = "Qiskit addon"
documentation = "https://qiskit.github.io/qiskit-addon-opt-mapper/"
uuid = "ef4e120a-f308-4462-86b6-10e7c7ba17c7"
badge = "https://qisk.it/e-ef4e120a"

[github]
url = "https://github.com/Qiskit/qiskit-addon-opt-mapper"
owner = "Qiskit"
repo = "qiskit-addon-opt-mapper"
stars = 14
homepage = "https://qiskit.github.io/qiskit-addon-opt-mapper/"
license = "Apache License 2.0"
description = "Mapping combinatorial optimization problems to quantum computers"
estimated_contributors = 23
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-04-14T07:30:00Z
last_activity = 2026-04-14T07:30:01Z

[checks.007]
since = 2026-04-08T16:22:37.450347
details = "the entry `member.interface` does not exist and it is mandatory"
importance = "CRITICAL"

[pypi.qiskit-addon-opt-mapper]
package_name = "qiskit-addon-opt-mapper"
version = "0.1.0"
last_release_date = 2025-11-03T14:17:55
license = "Apache-2.0"
url = "https://pypi.org/project/qiskit-addon-opt-mapper/"
requires_qiskit = "<3"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-03-13T02:30:30Z
highest_supported_qiskit_version = "2.3.1"
last_month_downloads = 989
last_180_days_downloads = 2992
