name = "qiskit-trev"
submission_number = 1090
url = "https://github.com/keunjunpark/qiskit-trev"
description = "GPU-accelerated quantum circuit simulation plugin for Qiskit using tensor ring representations, powered by PyTorch."
contact_info = "keunjunpark0925@gmail.com"
labels = [ "QML", "optimization", "HPC", "provider",]
interface = [ "Python",]
category = "Circuit simulator"
packages = []
uuid = "e2beb4ad-418d-4dca-b789-02567d385528"

[github]
url = "https://github.com/keunjunpark/qiskit-trev"
owner = "keunjunpark"
repo = "qiskit-trev"
stars = 1
license = "MIT License"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-04-14T20:40:51Z
last_activity = 2026-04-14T20:40:52Z

[pypi.qiskit-trev]
package_name = "qiskit-trev"
version = "0.1.0"
last_release_date = 2026-04-14T14:01:19
license = "MIT"
url = "https://pypi.org/project/qiskit-trev/"
requires_qiskit = ">=1.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-03-13T02:30:30Z
highest_supported_qiskit_version = "2.3.1"
last_month_downloads = 115
last_180_days_downloads = 115
