name = "Qiskit Quantum Machines Provider"
submission_number = 1053
url = "https://github.com/arthurostrauss/qiskit-qm-provider"
description = "Compile and execute complex Qiskit workflows on the Quantum Orchestration Platform and its pulse-level programming language QUA."
contact_info = "arthurostrauss@gmail.com"
labels = [ "openqasm", "provider", "research", "error correction", "HPC",]
interface = ["Python",]
category = "Compute provider"
documentation = "https://arthurostrauss.github.io/qiskit-qm-provider/"
packages = [ "https://pypi.org/project/qiskit-qm-provider/",]
uuid = "07ae12cb-5d1e-4d62-bc32-1d8ddfba748e"
