name = "qiskit-trev"
submission_number = 1090
url = "https://github.com/keunjunpark/qiskit-trev"
description = "GPU-accelerated quantum circuit simulation plugin for Qiskit using tensor ring representations, powered by PyTorch."
contact_info = "keunjunpark0925@gmail.com"
labels = [ "QML", "optimization", "HPC", "provider",]
interface = [ "Python",]
category = "Circuit simulator"
packages = []
uuid = "e2beb4ad-418d-4dca-b789-02567d385528"

[github]
owner = "keunjunpark"
repo = "qiskit-trev"

[pypi.qiskit-trev]
package_name = "qiskit-trev"
