name = "qMuVi"
url = "https://github.com/garymooney/qmuvi"
description = "Convert circuits into audiovisual experiences, bridging the gap between complex quantum computations and human perception."
licence = "GNU Library or \"Lesser\" General Public License (LGPL)"
contact_info = "gary.mooney4444@gmail.com"
affiliations = "The University of Melbourne"
labels = [ "demo",]
category = "Converter"
documentation = "https://garymooney.github.io/qmuvi/"
uuid = "9d4da903-9823-4ae3-a80c-22821b62931e"
badge = "https://qisk.it/e-9d4da903"

[github]
url = "https://github.com/garymooney/qmuvi"
owner = "garymooney"
repo = "qmuvi"
stars = 16
homepage = "https://garymooney.github.io/qmuvi/"
license = "GNU Lesser General Public License v2.1"
description = "qMuVi - A python package that converts quantum circuits into audiovisual experiences, bridging the gap between complex quantum comp..."
estimated_contributors = 4
total_dependent_repositories = 4
total_dependent_packages = 0
last_commit = 2025-11-19T05:20:57Z
last_activity = 2026-03-03T09:59:47Z

[checks.007]
since = 2026-04-08T16:22:36.418736
details = "the interface entry is mandatory"
importance = "CRITICAL"

[pypi.qmuvi]
package_name = "qmuvi"
version = "0.3.0"
last_release_date = 2025-09-04T08:33:57
url = "https://pypi.org/project/qmuvi/"
requires_qiskit = "<3.0.0,>=2.1.2"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-03-13T02:30:30Z
highest_supported_qiskit_version = "2.3.1"
last_month_downloads = 23
last_180_days_downloads = 310
