name = "qMuVi"
url = "https://github.com/garymooney/qmuvi"
description = "Convert circuits into audiovisual experiences, bridging the gap between complex quantum computations and human perception."
license = "GNU Library or \"Lesser\" General Public License (LGPL)"
contact_info = "gary.mooney4444@gmail.com"
affiliations = "The University of Melbourne"
labels = [ "demo",]
interfaces = [ "Python",]
category = "Converter"
documentation = "https://garymooney.github.io/qmuvi/"
packages = []
uuid = "9d4da903-9823-4ae3-a80c-22821b62931e"
maturity = "experimental"

[github]
url = "https://github.com/garymooney/qmuvi"
owner = "garymooney"
repo = "qmuvi"
stars = 17
homepage = "https://garymooney.github.io/qmuvi/"
license = "GNU Lesser General Public License v2.1"
description = "qMuVi - A python package that converts quantum circuits into audiovisual experiences, bridging the gap between complex quantum comp..."
estimated_contributors = 4
total_dependent_repositories = 4
total_dependent_packages = 0
last_commit = 2025-11-19
last_activity = 2026-06-09

[badge]
url = "https://qisk.it/e-9d4da903"
style = "flat"

[pypi.qmuvi]
package_name = "qmuvi"
version = "0.3.0"
last_release_date = 2025-09-04
description = "qMuVi is a Python library that converts quantum circuits into music videos, enabling visualisation of quantum state evolution through sound and animation. It supports noise models to simulate physical quantum devices and displays animating probability and phase distributions of basis states."
url = "https://pypi.org/project/qmuvi/"
development_status = "2 - Pre-Alpha"
requires_qiskit = "<3.0.0,>=2.1.2"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 62
last_180_days_downloads = 360
