name = "Qoffee"
submission_number = 1323
url = "https://github.com/saadbhattii/Qoffee"
description = "A free and open-source IBM quantum job monitoring and notification tool that runs as a GitHub Action in your own GitHub account."
contact_info = "bhatti150201@gmail.com"
labels = ["cloud service"]
interfaces = ["Python"]
category = "Tooling"
packages = []
uuid = "8f32b728-1f79-4421-ade2-6ce15b0cff29"
maturity = "production-ready"

[github]
owner = "saadbhattii"
repo = "Qoffee"
