name = "Qoffee"
submission_number = 1323
url = "https://github.com/saadbhattii/Qoffee"
description = "A free and open-source IBM quantum job monitoring and notification tool that runs as a GitHub Action in your own GitHub account."
contact_info = "bhatti150201@gmail.com"
labels = ["cloud service"]
interfaces = ["Command-line interface (CLI)", "Other interface"]
category = "Tooling"
packages = []
uuid = "8f32b728-1f79-4421-ade2-6ce15b0cff29"
maturity = "experimental"

[github]
url = "https://github.com/saadbhattii/Qoffee"
owner = "saadbhattii"
repo = "Qoffee"
stars = 3
homepage = "https://qiskit.github.io/ecosystem/p/8f32b728/"
license = "Apache-2.0"
description = "Qoffee is an open-source IBM quantum job monitoring and notification tool that runs as a GitHub Action in your own repository, on a..."
last_commit = 2026-09-04
last_activity = 2026-09-04
