name = "QSP-SQD"
submission_number = 1135
url = "https://github.com/JoelHBierman/QSP-SQD"
description = "This method enhances sample-based diagonalization (SQD) with quantum signal processing (QSP) to improve sampling-efficiency."
contact_info = "jhbierma@ncsu.edu"
labels = [ "chemistry", "physics", "quantum information", "circuit building", "research",]
interfaces = [ "Python",]
category = "Other"
pattern_steps = []
packages = []
uuid = "dbbc6636-2e4a-4c31-a7c8-e566e55d0cf9"
