name = "QSP-SQD"
submission_number = 1135
url = "https://github.com/JoelHBierman/QSP-SQD"
description = "Enhances sample-based diagonalization (SQD) with quantum signal processing (QSP) to improve sampling-efficiency."
contact_info = "jhbierma@ncsu.edu"
labels = [ "chemistry", "physics", "quantum information", "circuit building", "research",]
interfaces = [ "Python",]
category = "Other"
pattern_steps = []
packages = []
uuid = "f5cb686d-c6f7-4439-a5a2-0d13e7ac0bd1"
