name = "Quantum Debugger"
url = "https://github.com/quantag/qdb-qscore"
description = "Debug and visualize OpenQASM and Qiskit circuits directly from VSCode or any IDE that supports Microsoft's Debugger Adapter Protocol."
license = "MIT"
contact_info = "sergii.salata@quantag-it.com"
affiliations = "Quantag IT Solutions GmbH"
labels = ["openqasm"]
interfaces = ["Python", "Graphical User Interface (GUI)"]
website = "https://quantag-it.com/quantum/"
category = "Tooling"
packages = []
uuid = "3728ab3d-5b7b-416d-ad73-8e55a41091ca"
maturity = "production-ready"
status = "Under revision"

[github]
url = "https://github.com/quantag/qdb-qscore"
owner = "quantag"
repo = "qdb-qscore"
stars = 1
homepage = "https://quantum.quantag-it.com/"
license = "MIT"
description = "Quantum circuit debugger backend"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-01-19
last_activity = 2026-01-19

[badge]
url = "https://qisk.it/e-3728ab3d"
style = "flat"
