name = "Qiskit Quantum Machines Provider"
submission_number = 1053
url = "https://github.com/arthurostrauss/qiskit-qm-provider"
description = "Compile and execute complex Qiskit workflows on the Quantum Orchestration Platform and its pulse-level programming language QUA."
contact_info = "arthurostrauss@gmail.com"
labels = [ "openqasm", "provider", "research", "error correction", "HPC",]
interfaces = [ "Python",]
category = "Compute provider"
documentation = "https://arthurostrauss.github.io/qiskit-qm-provider/"
packages = []
uuid = "07ae12cb-5d1e-4d62-bc32-1d8ddfba748e"
maturity = "production-ready"

[github]
url = "https://github.com/arthurostrauss/qiskit-qm-provider"
owner = "arthurostrauss"
repo = "qiskit-qm-provider"
stars = 3
homepage = "https://arthurostrauss.github.io/qiskit-qm-provider/"
license = "Apache License 2.0"
description = "An interface enabling the compilation and execution of Qiskit workflows on Quantum Machine's Quantum Orchestration Platform"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-05-12T07:00:48Z
last_activity = 2026-05-12T07:00:49Z

[badge]
url = "https://qisk.it/e-07ae12cb"
style = "flat"

[pypi.qiskit-qm-provider]
package_name = "qiskit-qm-provider"
version = "0.1.0"
last_release_date = 2026-03-08T10:02:09
url = "https://pypi.org/project/qiskit-qm-provider/"
requires_qiskit = ">=0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24T22:41:40Z
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 17
last_180_days_downloads = 158
