name = "Quantum Fragment Methods"
submission_number = 1347
url = "https://github.com/qiskit-community/quantum-fragment-methods"
description = "A Python package for quantum chemistry tailored toward fragment-based embedding and quantum algorithms for macromolecules."
labels = ["chemistry"]
interfaces = ["Python"]
category = "Application"
reference_paper = "https://arxiv.org/abs/2512.17130"
packages = []
uuid = "cc4954fc-12f8-421c-833b-f8de1328cdc0"
maturity = "experimental"
status = "Under revision"

[github]
url = "https://github.com/qiskit-community/quantum-fragment-methods"
owner = "qiskit-community"
repo = "quantum-fragment-methods"
stars = 16
homepage = "https://arxiv.org/pdf/2512.17130"
license = "Apache-2.0"
description = " A Python package for quantum chemistry tailored toward fragment-based embedding and quantum algorithms applied to macromolecule si..."
created_at = 2026-04-15
last_commit = 2026-09-16
last_activity = 2026-09-28

[badge]
url = "https://qisk.it/e-cc4954fc"
style = "flat"

[python.quantum-fragment-methods]
package_name = "quantum-fragment-methods"
version = "0.0.1"
license = "Apache-2.0"
description = "Fragment-based Wavefunction Embedding framework for quantum simulation of macromolecules"
requires_python = ">=3.8"
requires_qiskit = ">=1.0.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-08-13
highest_supported_qiskit_version = "2.5.2"
build_backend = "setuptools.build_meta"
source = ["pyproject.toml"]
deferred = []

[checks.S02]
xfailed = "Issue asking for the cap submitted https://github.com/qiskit-community/quantum-fragment-methods/issues/13, waiting for the fix"
xfailed_until = 2027-03-31
since = 2026-09-28
details = "The distribution quantum-fragment-methods declared in the repository allows a not-yet-released major version of Qiskit"
discussion = "https://github.com/qiskit-community/quantum-fragment-methods/issues/13"
importance = "RECOMMENDATION"
