name = "Qiskit Quantum Load Balancer"
submission_number = 1362
url = "https://github.com/RexRowan/Qiskit-Quantum-LoadBalancer"
description = "Queue- and noise-aware backend selection and routing for IBM Quantum backends."
contact_info = "titaniumdavinci@gmail.com"
labels = ["provider", "cloud service", "utility-scale", "benchmarking"]
interfaces = ["Python"]
category = "Tooling"
packages = ["https://pypi.org/project/qiskit-quantum-loadbalancer"]
uuid = "b9729932-f4e7-43eb-9d91-0c55cd80c76f"
maturity = "experimental"
