name = "quantum-learn"
submission_number = 1275
url = "https://github.com/KUQCI/quantum-learn"
description = "Making quantum machine learning easier through higher-level estimators and quantum circuit wrappers for common workflows."
contact_info = "quantuminitiative.ku@gmail.com"
labels = ["QML"]
interfaces = ["Python"]
category = "SDK"
documentation = "https://quantum-learn.readthedocs.io/"
packages = []
uuid = "f07e354e-282f-41aa-99b3-0e36090de86a"
maturity = "experimental"

[github]
owner = "KUQCI"
repo = "quantum-learn"

[pypi.quantum-learn]
package_name = "quantum-learn"
