name = "Quantum Kernel Training"
url = "https://github.com/qiskit-community/prototype-quantum-kernel-training"
description = "Train and use quantum kernels for machine learning. For researchers and practitioners looking to explore and apply these algorithms."
license = "Apache-2.0"
labels = ["QML"]
interfaces = ["Python"]
created_at = 2022-02-21
category = "Application"
documentation = "https://github.com/qiskit-community/prototype-quantum-kernel-training/tree/main/docs"
packages = []
uuid = "6daa87ef-87ea-4dc9-aeed-3b9e8d202fd9"
maturity = "unmaintained"
status = "Under revision"

[github]
url = "https://github.com/qiskit-community/prototype-quantum-kernel-training"
owner = "qiskit-community"
repo = "prototype-quantum-kernel-training"
stars = 47
homepage = "https://arxiv.org/abs/2105.03406"
license = "Apache-2.0"
description = "Toolkit for training quantum kernels in machine learning applications"
estimated_contributors = 4
total_dependent_repositories = 0
total_dependent_packages = 0
archived = true
last_commit = 2024-03-31
last_activity = 2026-05-31

[badge]
url = "https://qisk.it/e-6daa87ef"
style = "flat"

[checks.G05]
since = 2026-07-23
details = "GitHub repository archived"
importance = "CRITICAL"

[checks.G07]
since = 2026-05-14
details = "Last commit was 27 months ago, which is more than 18 months ago. Please update the GitHub repository or set member.maturity to `as-is`."
discussion = "https://github.com/orgs/Qiskit/discussions/54"
importance = "STRONG-RECOMMENDATION"
