name = "Quantum Fragment Methods"
submission_number = 1347
url = "https://github.com/qiskit-community/quantum-fragment-methods"
description = "A Python package for quantum chemistry tailored toward fragment-based embedding and quantum algorithms for macromolecules."
labels = ["chemistry"]
interfaces = ["Python"]
category = "Application"
reference_paper = "https://arxiv.org/abs/2512.17130"
packages = []
uuid = "cc4954fc-12f8-421c-833b-f8de1328cdc0"
maturity = "experimental"
