name = "Qubit"
url = "https://github.com/R-D-BioTech-Alaska/Qubit"
description = "Implements real-world n-level Cubit (physics) and Qubit (Qiskit) abstractions with subspace, noise, and device realism."
license = "PolyForm-Strict-1.0.0"
contact_info = "contact@qelm.org"
affiliations = "R&D BioTech Alaska"
labels = ["research", "physics"]
interfaces = ["Python"]
category = "Circuit simulator"
packages = []
uuid = "5870b3e3-0c86-4506-aa73-1d6b1f172b7c"
maturity = "production-ready"
status = "Alumni"

[github]
url = "https://github.com/R-D-BioTech-Alaska/Qubit"
owner = "R-D-BioTech-Alaska"
repo = "Qubit"

[badge]
url = "https://qisk.it/e-5870b3e3"
style = "flat"

[checks.G09]
since = 2026-09-24
details = "member.github.license does not exist"
importance = "RECOMMENDATION"

[checks.O02]
since = 2026-09-24
details = "member.license is not OSI-approved"
importance = "IMPORTANT"

[checks.001]
since = 2026-07-30
source = "https://github.com/Qiskit/ecosystem/issues/1386"
details = "Qubit license is not open-source. It is a proprietary license that restricts usage and distribution. (the source issue is closed as completed)"
importance = "CRITICAL"
