name = "qiskit-qubit-reuse"
url = "https://github.com/qiskit-community/qiskit-qubit-reuse"
description = "A Qiskit transpiler stage plugin that reuses qubits through mid-circuit measurement and reset."
license = "Apache-2.0"
affiliations = "IBM"
labels = ["research", "circuit optimization"]
interfaces = ["Python"]
category = "Transpiler plugin"
packages = []
uuid = "c9369922-7e0d-4b77-b00a-329472b57a34"
maturity = "production-ready"

[github]
url = "https://github.com/qiskit-community/qiskit-qubit-reuse"
owner = "qiskit-community"
repo = "qiskit-qubit-reuse"
stars = 30
license = "Apache-2.0"
description = "A Qiskit transpiler stage plugin to enable qubit reuse via mid-circuit measurement and reset."
estimated_contributors = 3
total_dependent_repositories = 2
total_dependent_packages = 0
last_commit = 2025-07-03
last_activity = 2026-03-29

[badge]
url = "https://qisk.it/e-c9369922"
style = "flat"

[pypi.qiskit-qubit-reuse]
package_name = "qiskit-qubit-reuse"
version = "0.0.2"
last_release_date = 2024-02-05
license = "Apache-2.0"
description = "A Qiskit's compiler plugin to reuse qubits using midcircuit measurement"
url = "https://pypi.org/project/qiskit-qubit-reuse/"
status = "active"
maintainers = ["https://pypi.org/user/danielleodigie/"]
requires_qiskit = ">=0.43.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-07-02
highest_supported_qiskit_version = "2.5.0"
last_month_downloads = 45
last_180_days_downloads = 182

[checks.P10]
since = 2026-07-09
details = "Python package qiskit-qubit-reuse declared itself compatible to a not-yet-released major version of Qiskit"
importance = "RECOMMENDATION"
