name = "Qiskit Qulacs"
url = "https://github.com/Gopal-Dahale/qiskit-qulacs"
description = "Qiskit-Qulacs allows users to execute Qiskit programs using Qulacs backend."
license = "Apache-2.0"
contact_info = "dahalegopal27@gmail.com"
labels = ["provider"]
interfaces = ["Python"]
category = "Compute provider"
documentation = "https://qiskit-qulacs.netlify.app/"
packages = []
uuid = "ebd47aa6-4dda-4318-a822-dbd1597ed37a"
maturity = "production-ready"

[github]
url = "https://github.com/Gopal-Dahale/qiskit-qulacs"
owner = "Gopal-Dahale"
repo = "qiskit-qulacs"
stars = 10
homepage = "https://qiskit-qulacs.netlify.app/"
license = "Apache-2.0"
description = "Execute Qiskit programs using Qulacs backend."
estimated_contributors = 2
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-12-15
last_activity = 2025-12-15

[badge]
url = "https://qisk.it/e-ebd47aa6"
style = "flat"

[pypi.qiskit-qulacs]
package_name = "qiskit-qulacs"
version = "0.1.0"
last_release_date = 2024-04-02
license = "Apache-1.1"
description = "Qiskit Qulacs to execute Qiskit programs using Qulacs as backend."
url = "https://pypi.org/project/qiskit-qulacs/"
status = "active"
maintainers = ["https://pypi.org/user/gopald/"]
requires_qiskit = ">=1.0.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 183
last_180_days_downloads = 624

[checks.P10]
since = 2026-07-09
details = "Python package qiskit-qulacs declared itself compatible to a not-yet-released major version of Qiskit"
importance = "RECOMMENDATION"
