name = "QuPrep"
submission_number = 1118
url = "https://github.com/quprep/quprep"
description = "Quantum data preparation — the missing preprocessing layer between classical datasets and quantum computing frameworks."
contact_info = "hasarindu@quprep.org"
labels = [ "QML", "optimization", "circuit building", "research",]
interface = [ "Python", "Command-line interface (CLI)",]
website = "https://quprep.org"
category = "Tooling"
documentation = "https://docs.quprep.org"
packages = [ "https://pypi.org/project/quprep",]
uuid = "e993c3c7-09e9-4916-a3eb-fb4e9266bedf"
