name = "quPython"
url = "https://github.com/frankharkins/quPython"
description = "Write Pythonic quantum programs. Replace circuits and registers with functions and classes for better abstractions and readability."
license = "MIT"
contact_info = "frankharkins@hotmail.co.uk"
labels = ["circuit building"]
interfaces = ["Python"]
category = "SDK"
documentation = "https://frankharkins.github.io/quPython/"
packages = []
uuid = "bad95659-420a-4529-97d0-80e52532fc90"
maturity = "production-ready"

[github]
url = "https://github.com/frankharkins/quPython"
owner = "frankharkins"
repo = "quPython"
stars = 11
homepage = "https://frankharkins.github.io/quPython/"
license = "MIT"
description = "Quantum programs in Python"
estimated_contributors = 2
total_dependent_repositories = 5
total_dependent_packages = 0
last_commit = 2024-10-09
last_activity = 2026-01-31

[badge]
url = "https://qisk.it/e-bad95659"
style = "flat"

[pypi.qupython]
package_name = "qupython"
version = "0.2.0"
last_release_date = 2024-04-07
license = "MIT"
description = "Write quantum programs directly in Python"
url = "https://pypi.org/project/qupython/"
status = "active"
maintainers = ["https://pypi.org/user/frankharkins/"]
requires_qiskit = ">=0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 73
last_180_days_downloads = 158

[checks.G07]
since = 2026-05-14
details = "Last commit was 21 months ago, which is more than 18 months ago. Please update the GitHub repository or set member.maturity to `as-is`."
importance = "STRONG-RECOMMENDATION"

[checks.P10]
since = 2026-07-09
details = "Python package qupython declared itself compatible to a not-yet-released major version of Qiskit"
importance = "RECOMMENDATION"
