name = "Samplomatic"
submission_number = 1158
url = "https://github.com/Qiskit/samplomatic"
description = "Library for declarative quantum circuit randomization: Pauli twirling, noise injection, and extensible sampling via custom groups."
labels = [ "circuit building", "error mitigation",]
interfaces = [ "Python",]
category = "Qiskit addon"
pattern_steps = []
documentation = "https://qiskit.github.io/samplomatic/"
packages = []
uuid = "54222a2e-3d6b-4fdb-b21d-692eb0452a5e"
maturity = "experimental"

[github]
url = "https://github.com/Qiskit/samplomatic"
owner = "Qiskit"
repo = "samplomatic"
stars = 18
license = "Apache License 2.0"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-05-19T21:00:41Z
last_activity = 2026-05-20T07:29:46Z

[badge]
url = "https://qisk.it/e-54222a2e"
style = "flat"

[pypi.samplomatic]
package_name = "samplomatic"
version = "0.19.0"
last_release_date = 2026-05-19T16:36:49
license = "Apache-2.0"
url = "https://pypi.org/project/samplomatic/"
development_status = "3 - Alpha"
requires_qiskit = ">=2.3.0"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24T22:41:40Z
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 248903
last_180_days_downloads = 451029
