name = "Samplomatic"
submission_number = 1158
url = "https://samplomatic"
description = "Library for declarative quantum circuit randomization: Pauli twirling, noise injection, and extensible sampling via custom groups. aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
labels = [ "circuit building", "error mitigation",]
interfaces = [ "Python",]
category = "Qiskit addon"
pattern_steps = []
documentation = "https://qiskit.github.io/samplomatic/"
packages = []
uuid = "5aab2a5a-c51c-4b8b-b7bc-fe46de12c175"
maturity = "experimental"
