name = "Qiskit SAT Synthesis"
url = "https://github.com/qiskit-community/qiskit-sat-synthesis"
description = "Synthesis plugins for Cliffords, linear functions, permutations, and more."
licence = "Apache License 2.0"
contact_info = "alexi@il.ibm.com"
affiliations = "IBM"
labels = []
category = "High-level synthesis plugin"
uuid = "2e6b95b1-5046-4a83-8842-c0b6ea36ec12"
status = "Alumni"

[github]
url = "https://github.com/qiskit-community/qiskit-sat-synthesis"
owner = "qiskit-community"
repo = "qiskit-sat-synthesis"
stars = 9
license = "Apache License 2.0"
estimated_contributors = 2
total_dependent_repositories = 2
total_dependent_packages = 0
last_commit = 2026-03-29T12:17:06Z
last_activity = 2026-03-29T12:17:07Z

[badge]
url = "https://qisk.it/e-2e6b95b1"
style = "flat"

[checks.007]
since = 2026-04-08T16:23:00.945226
details = "the entry `member.interface` does not exist and it is mandatory"
discussion = "https://github.com/Qiskit/ecosystem/issues/1083"
importance = "CRITICAL"

[checks.008]
since = 2026-04-23T18:17:37.676459
details = "member.group should exist in labels.toml"
importance = "CRITICAL"

[pypi.qiskit-sat-synthesis]
package_name = "qiskit-sat-synthesis"
version = "0.0.2"
last_release_date = 2024-12-24T07:05:06
url = "https://pypi.org/project/qiskit-sat-synthesis/"
requires_qiskit = ">=1.2.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-16T19:34:58Z
highest_supported_qiskit_version = "2.4.0"
last_month_downloads = 15
last_180_days_downloads = 148
