name = "Qiskit Serverless"
url = "https://github.com/Qiskit/qiskit-serverless"
description = "Execute Qiskit programs as long-running jobs and distribute them across many CPUs, GPUs, and QPUs."
license = "Apache-2.0"
contact_info = "sanket@ibm.com"
labels = ["cloud service", "HPC", "GPU"]
interfaces = ["Python"]
ibm_maintained = true
created_at = 2022-12-07
category = "SDK"
documentation = "https://qiskit.github.io/qiskit-serverless/"
packages = []
uuid = "d463fcf2-9e98-4d16-af3b-25ec29b650f7"
maturity = "experimental"
status = "Qiskit Project"

[github]
url = "https://github.com/Qiskit/qiskit-serverless"
owner = "Qiskit"
repo = "qiskit-serverless"
stars = 113
homepage = "https://qiskit.github.io/qiskit-serverless/"
license = "Apache-2.0"
description = "A programming model for leveraging quantum and classical resources"
estimated_contributors = 31
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-07-13
last_activity = 2026-07-13

[badge]
url = "https://qisk.it/e-d463fcf2"
style = "flat"

[pypi.qiskit-serverless]
package_name = "qiskit-serverless"
version = "0.33.0"
last_release_date = 2026-07-09
license = "Apache-2.0"
description = "An open-source SDK for resource management in quantum computing workflows."
url = "https://pypi.org/project/qiskit-serverless/"
development_status = "3 - Alpha"
status = "active"
maintainers = ["https://pypi.org/org/qiskit/", "https://pypi.org/user/Tansito/"]
requires_qiskit = "<3,>=1.4"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 26861
last_180_days_downloads = 71954
