name = "Shaded Lightcones"
submission_number = 1172
url = "https://github.com/Qiskit/qiskit-addon-slc"
labels = [ "utility-scale", "error mitigation",]
interfaces = [ "Python",]
ibm_maintained = true
category = "Qiskit addon"
reference_paper = "https://arxiv.org/abs/2409.04401"
documentation = "https://qiskit.github.io/qiskit-addon-slc/"
packages = []
uuid = "189aa71b-6ad7-4c23-8ae5-81c369e415b3"
maturity = "experimental"
status = "Qiskit Project"

[github]
url = "https://github.com/Qiskit/qiskit-addon-slc"
owner = "Qiskit"
repo = "qiskit-addon-slc"
stars = 5
homepage = "https://qiskit.github.io/qiskit-addon-slc/"
license = "Apache-2.0"
description = "Reducing PEC sampling overhead with shaded lightcones"
estimated_contributors = 9
total_dependent_repositories = 1
total_dependent_packages = 0
last_commit = 2026-07-01
last_activity = 2026-07-02

[badge]
url = "https://qisk.it/e-189aa71b"
style = "flat"

[pypi.qiskit-addon-slc]
package_name = "qiskit-addon-slc"
version = "0.1.0"
last_release_date = 2025-11-06
license = "Apache-2.0"
description = "Reducing PEC sampling overhead with shaded lightcones"
url = "https://pypi.org/project/qiskit-addon-slc/"
status = "active"
maintainers = [ "https://pypi.org/org/qiskit/",]
requires_qiskit = "<3,>=2.2"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 605
last_180_days_downloads = 778
