name = "Spank plugins for Slurm"
url = "https://github.com/qiskit-community/spank-plugins"
description = "Slurm SPANK plugins that make quantum devices schedulable resources inside HPC batch jobs."
labels = ["HPC", "cloud service"]
interfaces = ["Other", "Command-line interface (CLI)"]
category = "Tooling"
packages = []
uuid = "d7ae5877-de0b-48f3-9f56-460c4f629647"
maturity = "experimental"

[github]
url = "https://github.com/qiskit-community/spank-plugins"
owner = "qiskit-community"
repo = "spank-plugins"
stars = 58
license = "GPL-3.0"
description = "Slurm Spank plugins for Quantum resources and jobs support"
last_commit = 2026-08-14
last_activity = 2026-08-14

[badge]
url = "https://qisk.it/e-d7ae5877"
style = "flat"
