name = "Spank plugins for Slurm"
url = "https://github.com/qiskit-community/spank-plugins"
description = "Slurm SPANK plugins that make quantum devices schedulable resources inside HPC batch jobs."
labels = ["HPC", "cloud service"]
interfaces = ["C", "Command-line interface (CLI)"]
category = "Tooling"
packages = []
uuid = "d7ae5877-de0b-48f3-9f56-460c4f629647"
maturity = "experimental"

[github]
owner = "qiskit-community"
repo = "spank-plugins"

[badge]
url = "https://qisk.it/e-d7ae5877"
style = "flat"
