name = "Sample-based Quantum Diagonalization"
url = "https://github.com/Qiskit/qiskit-addon-sqd"
description = "Sample-based quantum diagonalization. Classically postprocess noisy quantum samples to yield more accurate eigenvalue estimations."
labels = [ "chemistry", "utility-scale",]
interfaces = [ "Python",]
ibm_maintained = true
created_at = 1758737407.8760931
category = "Qiskit addon"
pattern_steps = [ "Post-process",]
documentation = "https://qiskit.github.io/qiskit-addon-sqd/"
packages = []
uuid = "fe036eac-635d-46db-931e-2965a8a138a5"
maturity = "experimental"
status = "Qiskit Project"

[github]
url = "https://github.com/Qiskit/qiskit-addon-sqd"
owner = "Qiskit"
repo = "qiskit-addon-sqd"
stars = 95
homepage = "https://qiskit.github.io/qiskit-addon-sqd/"
license = "Apache License 2.0"
description = "Sample-based Quantum Diagonalization: Classically postprocess noisy quantum samples to yield more accurate eigenvalue estimations."
estimated_contributors = 17
total_dependent_repositories = 13
total_dependent_packages = 2
last_commit = 2026-07-01
last_activity = 2026-07-01

[badge]
url = "https://qisk.it/e-fe036eac"
style = "flat"

[pypi.qiskit-addon-sqd]
package_name = "qiskit-addon-sqd"
version = "0.12.1"
last_release_date = 2026-01-16
description = "Classically postprocess noisy quantum samples to yield more accurate energy estimations"
url = "https://pypi.org/project/qiskit-addon-sqd/"
requires_qiskit = "<3,>=1.2"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 25189
last_180_days_downloads = 53967
