name = "qiskit-superstaq"
url = "https://github.com/Infleqtion/client-superstaq/tree/main/qiskit-superstaq"
description = "Access the SuperstaQ web API through Qiskit for applications, pulse-level optimizations, and write-once-target-all features."
license = "Apache-2.0"
contact_info = ""
labels = ["provider", "cloud service", "circuit optimization"]
interfaces = ["Python"]
created_at = 2023-03-14
category = "Compute provider"
documentation = "https://superstaq.readthedocs.io/"
packages = [
  "https://pypi.org/project/qiskit-superstaq/",
  "https://pypi.org/project/checks-superstaq/",
  "https://pypi.org/project/cirq-superstaq/",
  "https://pypi.org/project/general-superstaq/",
  "https://pypi.org/project/Supermarq/",
]
uuid = "76ae525f-0734-405b-b4b8-421f74125fa2"
maturity = "production-ready"

[github]
url = "https://github.com/Infleqtion/client-superstaq"
owner = "Infleqtion"
repo = "client-superstaq"
tree = "main/qiskit-superstaq"
stars = 130
license = "Apache-2.0"
description = "https://superstaq.readthedocs.io"
estimated_contributors = 38
total_dependent_repositories = 33
total_dependent_packages = 3
created_at = 2022-02-22
last_commit = 2026-10-08
last_activity = 2026-10-08

[badge]
url = "https://qisk.it/e-76ae525f"
style = "flat"

[[pypi]]
package_name = "checks-superstaq"
version = "0.5.70"
last_release_date = 2026-09-30
license = "Apache-2.0"
description = "Check script tools for Superstaq."
url = "https://pypi.org/project/checks-superstaq/"
status = "active"
maintainers = ["https://pypi.org/user/vtomole/"]
last_month_downloads = 6524
last_180_days_downloads = 57474

[[pypi]]
package_name = "cirq-superstaq"
version = "0.5.70"
last_release_date = 2026-09-30
license = "Apache-2.0"
description = "The Cirq module that provides tools and access to Superstaq."
url = "https://pypi.org/project/cirq-superstaq/"
status = "active"
maintainers = [
  "https://pypi.org/user/pranavgokhale/",
  "https://pypi.org/user/richrines/",
  "https://pypi.org/user/vtomole/",
]
last_month_downloads = 5385
last_180_days_downloads = 57493

[[pypi]]
package_name = "general-superstaq"
version = "0.5.70"
last_release_date = 2026-09-30
license = "Apache-2.0"
description = "The general module that provides tools and access to Superstaq."
url = "https://pypi.org/project/general-superstaq/"
status = "active"
maintainers = ["https://pypi.org/user/vtomole/"]
last_month_downloads = 5569
last_180_days_downloads = 59355

[[pypi]]
package_name = "qiskit-superstaq"
version = "0.5.70"
last_release_date = 2026-09-30
license = "Apache-2.0"
description = "The Qiskit module that provides tools and access to Superstaq."
url = "https://pypi.org/project/qiskit-superstaq/"
status = "active"
maintainers = [
  "https://pypi.org/user/pranavgokhale/",
  "https://pypi.org/user/richrines/",
  "https://pypi.org/user/vtomole/",
]
requires_qiskit = "<3,>=1.3.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 3430
last_180_days_downloads = 38768

[[pypi]]
package_name = "supermarq"
version = "0.5.70"
last_release_date = 2026-09-30
license = "Apache-2.0"
description = "Supermarq is a scalable, application-centric quantum benchmarking suite."
url = "https://pypi.org/project/Supermarq/"
status = "active"
maintainers = ["https://pypi.org/user/vtomole/"]
last_month_downloads = 663
last_180_days_downloads = 7124
