name = "symbolic-qiskit"
url = "https://github.com/ianchung621/symbolic-qiskit"
description = "Symbolic simulator for Qiskit circuits using sympy backend, supporting mid-circuit measurement and state inspection."
license = "Apache-2.0"
contact_info = "ianchung621@gmail.com"
affiliations = "National Taiwan University, Physics"
labels = ["quantum information"]
interfaces = ["Python"]
category = "Circuit simulator"
documentation = "https://github.com/ianchung621/symbolic-qiskit/tree/main/docs"
packages = []
uuid = "e10b8307-99fd-4d10-a046-3934bf9396a1"
maturity = "production-ready"

[github]
url = "https://github.com/ianchung621/symbolic-qiskit"
owner = "ianchung621"
repo = "symbolic-qiskit"
stars = 2
license = "Apache-2.0"
description = "Symbolic simulator for Qiskit circuits using sympy backend, supporting mid-circuit measurement and state inspection."
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-06-27

[badge]
url = "https://qisk.it/e-e10b8307"
style = "flat"

[checks.P10]
since = 2026-07-09T11:29:53.067305
details = "Python package symbolic-qiskit declared itself compatible to a not-yet-released major version of Qiskit"
importance = "RECOMMENDATION"

[pypi.symbolic-qiskit]
package_name = "symbolic-qiskit"
version = "0.1.0a1"
last_release_date = 2025-06-27
license = "Apache-2.0"
description = "Symbolic simulator for qiskit circuits using sympy backend, supporting mid-circuit measurement and state inspection."
url = "https://pypi.org/project/symbolic-qiskit/"
status = "active"
maintainers = ["https://pypi.org/user/ianchung621/"]
requires_qiskit = ">=0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 18
last_180_days_downloads = 103
