name = "TorchQuantum"
url = "https://github.com/mit-han-lab/torchquantum"
description = "A PyTorch-centric hybrid classical-quantum dynamic neural networks framework."
licence = "Apache 2.0"
labels = [ "QML",]
created_at = 1678827878.611621
updated_at = 1678827878.611622
category = "Application"
uuid = "6fefeede-f98e-44df-aea0-149827358701"
maturity = "production-ready"

[github]
url = "https://github.com/mit-han-lab/torchquantum"
owner = "mit-han-lab"
repo = "torchquantum"
stars = 1624
homepage = "https://torchquantum.org"
license = "MIT License"
description = "A PyTorch-based framework for Quantum Classical Simulation, Quantum Machine Learning, Quantum Neural Networks, Parameterized Quantu..."
estimated_contributors = 30
total_dependent_repositories = 61
total_dependent_packages = 1
last_commit = 2025-10-28T01:51:40Z
last_activity = 2026-04-26T10:20:08Z

[badge]
url = "https://qisk.it/e-6fefeede"
style = "flat"

[checks.007]
since = 2026-04-08T16:22:47.505314
details = "the entry `member.interface` does not exist and it is mandatory"
discussion = "https://github.com/Qiskit/ecosystem/issues/1083"
importance = "IMPORTANT"

[checks.PQ1]
since = 2026-04-30T11:32:49.789583
details = "assert False"
importance = "CRITICAL"

[checks.PQ2]
since = 2026-04-30T11:32:49.789583
details = "Python package torchquantum is not compatible with Qiskit SDK v2"
importance = "IMPORTANT"

[pypi.torchquantum]
package_name = "torchquantum"
version = "0.1.8"
last_release_date = 2024-02-21T19:31:20
url = "https://pypi.org/project/torchquantum/"
requires_qiskit = "<1.0.0,>=0.39.0"
compatible_with_qiskit_v1 = false
compatible_with_qiskit_v2 = false
highest_supported_qiskit_release_date = 2024-09-27T11:19:37Z
highest_supported_qiskit_version = "0.46.3"
last_month_downloads = 727
last_180_days_downloads = 8639
