name = "Qiskit Transpile Verify"
submission_number = 1315
url = "https://github.com/RexRowan/Qiskit-Transpile-Verify"
description = "Translation validation for the Qiskit transpiler"
contact_info = "titaniumdavinci@gmail.com"
labels = ["quantum information", "circuit optimization", "research"]
interfaces = ["Python"]
category = "Tooling"
packages = []
uuid = "f912d0ae-3944-4279-9ee5-60a4808794b5"
maturity = "experimental"

[github]
owner = "RexRowan"
repo = "Qiskit-Transpile-Verify"
