name = "Qiskit Transpile Verify"
submission_number = 1315
url = "https://github.com/RexRowan/Qiskit-Transpile-Verify"
description = "Translation validation for the Qiskit transpiler"
contact_info = "titaniumdavinci@gmail.com"
labels = ["quantum information", "research"]
interfaces = ["Python"]
category = "Tooling"
packages = ["https://pypi.org/project/qiskit-transpile-verify/"]
uuid = "f912d0ae-3944-4279-9ee5-60a4808794b5"
maturity = "experimental"

[github]
url = "https://github.com/RexRowan/Qiskit-Transpile-Verify"
owner = "RexRowan"
repo = "Qiskit-Transpile-Verify"
stars = 0
license = "Apache-2.0"
description = "Translation validation for the Qiskit transpiler"
last_commit = 2026-08-20
last_activity = 2026-08-20

[badge]
url = "https://qisk.it/e-f912d0ae"
style = "flat"
