name = "Variational Quantum Linear Solver Prototype"
url = "https://github.com/QuantumApplicationLab/vqls-prototype"
description = "VQLS uses an optimization approach to solve systems of linear equations. Set up and deploy VQLS instances on different backends."
licence = "Apache License 2.0"
contact_info = "nicolas.gm.renaud@gmail.com"
affiliations = "Netherlands eScience Center @ Quantum Application Lab, Amsterdam NL"
labels = [ "optimization",]
created_at = 1683906067.55753
updated_at = 1683906067.557535
category = "Application"
uuid = "05140a48-184b-491e-ac3c-d613ca05b3c8"
badge = "https://qisk.it/e-05140a48"

[github]
url = "https://github.com/QuantumApplicationLab/vqls-prototype"
owner = "QuantumApplicationLab"
repo = "vqls-prototype"
stars = 22
license = "Apache License 2.0"
description = "A Variational Quantum Linear Solver Prototype for Qiskit"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2024-11-27T16:59:01Z
last_activity = 2026-04-11T06:48:04Z

[checks.007]
since = 2026-04-08T16:22:54.329964
details = "the entry `member.interface` does not exist and it is mandatory"
discussion = "https://github.com/Qiskit/ecosystem/issues/1083"
importance = "CRITICAL"

[pypi.vqls-prototype]
package_name = "vqls-prototype"
version = "0.2.0"
last_release_date = 2023-11-03T09:09:05
url = "https://pypi.org/project/vqls-prototype/"
requires_qiskit = ">=0.14.1"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-03-13T02:30:30Z
highest_supported_qiskit_version = "2.3.1"
last_month_downloads = 47
last_180_days_downloads = 828
