name = "Variational Quantum Linear Solver Prototype"
url = "https://github.com/QuantumApplicationLab/vqls-prototype"
description = "VQLS uses an optimization approach to solve systems of linear equations. Set up and deploy VQLS instances on different backends."
license = "Apache-2.0"
contact_info = "nicolas.gm.renaud@gmail.com"
affiliations = "Netherlands eScience Center @ Quantum Application Lab, Amsterdam NL"
labels = [ "optimization",]
interfaces = [ "Python",]
created_at = 2023-05-12
category = "Application"
packages = []
uuid = "05140a48-184b-491e-ac3c-d613ca05b3c8"
maturity = "production-ready"

[github]
url = "https://github.com/QuantumApplicationLab/vqls-prototype"
owner = "QuantumApplicationLab"
repo = "vqls-prototype"
stars = 23
license = "Apache-2.0"
description = "A Variational Quantum Linear Solver Prototype for Qiskit"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2024-11-27
last_activity = 2026-06-15

[badge]
url = "https://qisk.it/e-05140a48"
style = "flat"

[checks.P12]
since = 2026-07-06T12:46:29.207233
details = "member.pypi.vqls-prototype does not have a declared license"
importance = "RECOMMENDATION"

[pypi.vqls-prototype]
package_name = "vqls-prototype"
version = "0.2.0"
last_release_date = 2023-11-03
description = "Repository for a quantum prototype"
url = "https://pypi.org/project/vqls-prototype/"
status = "active"
maintainers = [ "https://pypi.org/user/nico_reno/",]
requires_qiskit = ">=0.14.1"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-04-24
highest_supported_qiskit_version = "2.4.1"
last_month_downloads = 45
last_180_days_downloads = 237
