name = "Witching Hour"
submission_number = 1089
url = "https://github.com/witchinghourartcollective/witching-hour-qiskit"
description = "Minimal qBraid + Qiskit starter package for running circuits, discovering devices, and submitting first quantum jobs."
contact_info = "fletchervaughn@witchinghourmac.com"
labels = [ "circuit manipulation", "openqasm", "circuit building", "provider",]
interface = [ "Python",]
website = "https://witchinghourmac.com"
category = "Tooling"
packages = []
uuid = "5907eb1e-6ecd-4d5b-9f28-f302b23ace0e"

[github]
url = "https://github.com/witchinghourartcollective/witching-hour-qiskit"
owner = "witchinghourartcollective"
repo = "witching-hour-qiskit"
stars = 0
license = "MIT License"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-04-10T17:49:34Z
last_activity = 2026-04-10T17:49:35Z
