name = "Witching Hour"
submission_number = 1089
url = "https://github.com/witchinghourartcollective/witching-hour-qiskit"
description = "Minimal qBraid + Qiskit starter package for running circuits, discovering devices, and submitting first quantum jobs."
contact_info = "fletchervaughn@witchinghourmac.com"
labels = [ "circuit manipulation", "openqasm", "circuit building", "provider",]
interface = [ "Python",]
website = "https://witchinghourmac.com"
category = "Tooling"
uuid = "5907eb1e-6ecd-4d5b-9f28-f302b23ace0e"
