name = "arvak-lite"
submission_number = 1036
url = "https://github.com/hiq-lab/arvak-lite"
description = "Drop-in Qiskit transpiler plugin powered by a Rust-native compiler. 34x faster circuit optimization."
contact_info = "daniel@hal-contract.org"
labels = [ "circuit manipulation", "Rust", "optimization", "HPC",]
website = "https://arvak.io"
group = "Transpiler plugin"
packages = []
uuid = "7fcadf8b-f043-4eac-a491-9783a1c00cfe"

[github]
url = "https://github.com/hiq-lab/arvak-lite"
owner = "hiq-lab"
repo = "arvak-lite"
stars = 0
license = "GNU Lesser General Public License v3.0"
description = "Arvak quantum circuit compiler exposed as a transpiler plugin for Qiskit."
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-03-08T14:02:22Z
last_activity = 2026-03-08T14:02:29Z

[pypi.arvak-lite]
package_name = "arvak-lite"
version = "0.1.1"
last_release_date = 2026-03-08T14:02:53
url = "https://pypi.org/project/arvak-lite/"
requires_qiskit = ">=1.0.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-03-13T02:30:30Z
highest_supported_qiskit_version = "2.3.1"
last_month_downloads = 235
last_180_days_downloads = 235
