name = "arvak-lite"
submission_number = 1036
url = "https://github.com/hiq-lab/arvak-lite"
description = "Drop-in Qiskit transpiler plugin powered by a Rust-native compiler. 34x faster circuit optimization."
contact_info = "daniel@hal-contract.org"
labels = [ "circuit manipulation", "Rust", "optimization", "HPC",]
website = "https://arvak.io"
group = "Transpiler plugin"
packages = []
uuid = "7fcadf8b-f043-4eac-a491-9783a1c00cfe"

[github]
owner = "hiq-lab"
repo = "arvak-lite"

[pypi.arvak-lite]
package_name = "arvak-lite"
