name = "Double Quant"
submission_number = 1070
url = "https://github.com/11D-Beyonder/double-quant"
description = "Double Quant means (Qunat)um (Quant)itative, which is a high-performance quantum computing framework for solving quantitative finance problems."
contact_info = "ztz20001117@gmail.com"
labels = [ "finance",]
group = "Application"
packages = [ "https://pypi.org/project/double-quant/",]
uuid = "6e4e5010-7f25-4f03-9724-c9088b4ce0e0"
