name = "Torsion is the New Black"
url = "https://github.com/AnnaMariaDebniakSorensen/GENESIS"
description = "Prototype quantum circuits modeling torsion-inspired Hamiltonians with VQE, Trotter evolution, and QAOA."
licence = "Apache License 2.0"
contact_info = "Annamaria.debniak.sorensen@gmail.com"
labels = []
ibm_maintained = false
group = "other"
reference_paper = "https://share.google/m4hQzLnTpjDvvxe82"
uuid = "a9cc8e2c-637a-4361-bdf9-eba55d9317e2"
