name = "GULPS"
submission_number = 1061
url = "https://github.com/evmckinney9/gulps"
description = "Compile two-qubit unitaries into arbitrary ISAs"
contact_info = "evmckinney9@gmail.com"
labels = [ "Rust", "circuit building",]
group = "Transpiler plugin"
reference_paper = "https://arxiv.org/abs/2505.00543"
packages = [ "https://pypi.org/project/gulps/",]
uuid = "0a8128d0-2398-411b-a08e-737e2b198387"
