name = "MQT QAO"
url = "https://github.com/cda-tum/mqt-qao"
description = "Translate optimization problems into quantum-compliant formats and solve them with major quantum solvers."
licence = "MIT license"
contact_info = "quantum.cda@xcit.tum.de"
affiliations = "Technical University of Munich (TUM), Germany Politecnico di Torino, Italy"
labels = [ "circuit manipulation", "optimization",]
group = "Application"
reference_paper = "https://arxiv.org/abs/2406.12840"
documentation = "https://mqt.readthedocs.io/projects/qao/en/latest/"
uuid = "6d4c69e4-1e47-486c-b00f-8a60ae5e01d4"
badge = "https://qisk.it/e-6d4c69e4"

[github]
url = "https://github.com/cda-tum/mqt-qao"
owner = "cda-tum"
repo = "mqt-qao"
stars = 28
license = "MIT License"
description = "MQT Quantum Auto Optimizer - A MQT Tool for Solving Optimization Problems with Quantum Computers"
estimated_contributors = 7
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-03-23T17:30:05Z
last_activity = 2026-03-23T17:30:07Z

[pypi."mqt.qao"]
package_name = "mqt-qao"
version = "0.3.0"
last_release_date = 2024-12-01T10:52:55
license = "MIT License  Copyright (c) 2024 Deborah Volpe, Nils Quetschlich, Mariagrazia Graziano, Giovanna Turvani and Robert Wille  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the \"Software\"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:  The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.  THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. "
url = "https://pypi.org/project/mqt.qao/"
requires_qiskit = ">=1.0"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-03-13T02:30:30Z
highest_supported_qiskit_version = "2.3.1"
last_month_downloads = 29
last_180_days_downloads = 199
