name = "passing3"
submission_number = 383
url = "https://passing3"
description = "passing3"
labels = [ "error mitigation",]
group = "Converter"
packages = []
uuid = "d1b9d504-71f6-469c-8e67-ed27d737ca75"
