name = "qb-compiler"
submission_number = 1044
url = "https://github.com/mwpwalshe/qb-compiler"
description = "Quantum execution intelligence toolkit for circuit viability checks, backend analysis, calibration-aware compilation, and hardware-aware execution workflows."
contact_info = "michael.walshe@qubitboost.io"
labels = [ "optimization", "circuit manipulation", "error mitigation",]
website = "https://qubitboost.io/compiler"
group = "Transpiler plugin"
documentation = "https://github.com/mwpwalshe/qb-compiler#readme"
packages = [ "https://pypi.org/project/qb-compiler/",]
uuid = "d701fdb7-2e79-4f7e-a4d3-6bdc3c44871c"
