name = "QELM"
url = "https://github.com/R-D-BioTech-Alaska/Qelm"
description = "An innovative project that merges the power of quantum computing with natural language processing to create a next-generation language model. Leveraging Qiskit and Qiskit Aer, QELM explores the potential of quantum circuits in enhancing language understanding and generation capabilities. Utilizing Qubits, Qelm can train a model that would normally take up gigabytes worth of data in llm files all the way down to miniature sizes. With this size, llm's can run instantly with no loss of capabilities or intelligence and on small computers instead requiring data centers to run single models. The goal is to create llm's that are instant, smarter and can be utilized anywhere and by anyone."
licence = "MIT license"
contact_info = "contact@rdbiotechalaska.com"
affiliations = "R&D BioTech Alaska"
labels = [ "Machine learning",]
ibm_maintained = false
group = "applications"
uuid = "040b49a8-71be-4374-a12f-a38f63cbd567"
