name = "Qiskit Optimization"
url = "https://github.com/qiskit-community/qiskit-optimization"
description = "Model optimization problems, convert them between different representations, and solve them with quantum algorithms."
licence = "Apache 2.0"
labels = [ "optimization",]
created_at = 1636403009.538761
updated_at = 1636403009.538763
category = "Application"
documentation = "https://qiskit-community.github.io/qiskit-optimization/"
uuid = "3b2ff33f-b4a3-49cd-ab32-563d282cc3bf"
badge = "https://qisk.it/e-3b2ff33f"

[github]
url = "https://github.com/qiskit-community/qiskit-optimization"
owner = "qiskit-community"
repo = "qiskit-optimization"
stars = 279
homepage = "https://qiskit-community.github.io/qiskit-optimization/"
license = "Apache License 2.0"
description = "Quantum Optimization"
total_dependent_repositories = 411
total_dependent_packages = 41
last_commit = 2026-04-01T05:54:16Z
last_activity = 2026-04-01T05:54:16Z

[pypi.qiskit-optimization]
package_name = "qiskit-optimization"
version = "0.7.0"
last_release_date = 2025-08-20T14:04:16
url = "https://pypi.org/project/qiskit-optimization/"
requires_qiskit = "<3,>=1.1"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-03-13T02:30:30Z
highest_supported_qiskit_version = "2.3.1"
last_month_downloads = 35329
last_180_days_downloads = 197771
