name = "QuPepFold"
url = "https://github.com/akshayuttarkarc/QuPepFold"
description = "Research-oriented toolkit for turning amino-acid sequences into quantum bitstring encodings. Peer-reviewed and published in PLOS ONE."
licence = "MIT license"
contact_info = "akshayuttarkar@gmail.com"
affiliations = "R V College of Engineering MIT Vishwaprayag University"
labels = [ "chemistry",]
group = "Paper artifact"
reference_paper = "https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0342012"
uuid = "ab89baa7-39e9-482a-8157-a9bb834c5108"
badge = "https://qisk.it/e-ab89baa7"

[github]
url = "https://github.com/akshayuttarkarc/QuPepFold"
owner = "akshayuttarkarc"
repo = "QuPepFold"
stars = 1
license = "MIT License"
description = "QupepFold is a small, research-oriented toolkit that turns short amino-acid sequences into quantum bitstring encodings, optimizes t..."
estimated_contributors = 2
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2026-02-09T06:24:23Z
last_activity = 2026-03-17T12:09:03Z

[pypi.qupepfold]
package_name = "qupepfold"
version = "0.8.0"
last_release_date = 2026-02-04T09:21:25
url = "https://pypi.org/project/qupepfold/"
requires_qiskit = ">=0.39"
compatible_with_qiskit_v1 = true
compatible_with_qiskit_v2 = true
highest_supported_qiskit_release_date = 2026-03-13T02:30:30Z
highest_supported_qiskit_version = "2.3.1"
last_month_downloads = 99
last_180_days_downloads = 865
