name = "Implicit Solvent Model template"
url = "https://github.com/qiskit-community/qiskit-function-templates/tree/main/chemistry/sqd_pcm"
description = "A Qiskit Function template for the Implicit Solvent Model with SQD Qiskit addon, from IBM Quantum partnership with Cleveland Clinic"
licence = "Apache License 2.0"
affiliations = "Cleveland Clinic"
labels = [ "Applications",]
ibm_maintained = false
group = "applications"
reference_paper = "https://pubs.acs.org/doi/10.1021/acs.jpcb.5c01030"
uuid = "39a390ed-0608-4bcd-8e4b-48c7aaa0a9db"
