name = "Test Project"
submission_number = 1033
url = "https://github.com/Qiskit/ecosystem/"
description = "This is a test submission, to check if the new tokens are working."
labels = []
ibm_maintained = true
group = "Other"
packages = []
uuid = "eb224fd9-c537-4ef5-a2b9-b1dd34b84727"

[github]
owner = "Qiskit"
repo = "ecosystem"
