name = "Test Project"
submission_number = 1031
url = "https://github.com/Qiskit/ecosystem/"
description = "This is a test submission, to check if the new tokens are working"
labels = [ "openqasm",]
ibm_maintained = true
group = "Other"
packages = []
uuid = "c9f26201-aa58-4a8f-8170-b2d5eaafa664"

[github]
owner = "Qiskit"
repo = "ecosystem"
