name: Ecosystem | Submission

on:
  issues:
    types: [opened, edited, reopened]

jobs:
  submission_workflow:
    if: (startsWith(github.event.issue.title, '[Submission]:'))
    runs-on: ubuntu-latest
    env:
      python-version: "3.13"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Parse submission
      id: parse-issue
      env:
        ISSUE_BODY: ${{ github.event.issue.body }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
      run: python manager.py ci add_member_from_issue --body="$ISSUE_BODY" --number=$ISSUE_NUMBER

    - name: Validate submission
      id: valid-issue
      run: |
        python manager.py ci create_sections ${{ steps.parse-issue.outputs.SUBMISSION_SHORT_UUID }}
        python manager.py ci validate_new_member_yml ${{ steps.parse-issue.outputs.SUBMISSION_SHORT_UUID }}

    - name: Commit changes and create pull request
      id: cpr
      uses: peter-evans/create-pull-request@v7
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
      with:
        commit-message: Submission - Add ${{ steps.parse-issue.outputs.SUBMISSION_NAME }} to the Qiskit Ecosystem.
        title: Nominate ${{ steps.parse-issue.outputs.SUBMISSION_NAME }} to the Qiskit Ecosystem
        body: |
          Nomination for: ${{ steps.parse-issue.outputs.SUBMISSION_NAME }}
          
          By @${{ github.event.issue.user.login }}, via #${{ github.event.issue.number }}

        branch: submission-${{ steps.parse-issue.outputs.SUBMISSION_SHORT_UUID }}
        labels: submission

    - name: Find Comment bot comment
      uses: peter-evans/find-comment@v3
      if: always()
      id: fc
      with:
        issue-number: ${{ github.event.issue.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Check out the logs

    - name: Make comment on validated submission
      if: success() && steps.cpr.outputs.pull-request-number
      uses: peter-evans/create-or-update-comment@v5
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        edit-mode: replace
        body: |
          The submission is validated :white_check_mark:
          
          Let's close this issue in favor of the PR #${{ steps.cpr.outputs.pull-request-number }}. We can move the conversation about this project there.

          > [!IMPORTANT]  
          > The submitted project is not yet approved. It will be once PR #${{ steps.cpr.outputs.pull-request-number }} is reviewed and merged.
          > You can still make changes as code comments in that PR.
           
          <sub>Curious about the submission validation? [Check out the logs here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ job.check_run_id }}).</sub>

    - name: Close Issue
      run: gh issue close ${{ github.event.issue.number }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Make comment on failed submission
      if: failure()
      uses: peter-evans/create-or-update-comment@v5
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        edit-mode: replace
        body: |
          The submission failed :x:

          [Check out the logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ job.check_run_id }}).

          > [!TIP]
          > Edit the issue (using the ellipsis button on the upper-right corner) and try to fix the problems in the data validation.
          > The validation will re-run automatically after that. Once the validations pass, this issue will be closed and a PR will be created.
