name: Ecosystem | Submission

on:
  issues:
    types: [opened, edited, reopened]

jobs:
  submission_workflow:
    if: (startsWith(github.event.issue.title, '[Submission]:'))
    runs-on: ubuntu-latest
    env:
      tox_env: "py313"
      python-version: "3.13"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Parse submission
      id: parse-issue
      env:
        ISSUE_BODY: ${{ github.event.issue.body }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
      run: python manager.py ci add_member_from_issue --body="$ISSUE_BODY" --number=$ISSUE_NUMBER

    - name: Find Comment bot comment
      uses: peter-evans/find-comment@v3
      if: always()
      id: fc
      with:
        issue-number: ${{ github.event.issue.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Check out the logs

    - name: Commit changes and create pull request
      id: cpr
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: Submission - Add ${{ steps.parse-issue.outputs.SUBMISSION_NAME }} to the Qiskit Ecosystem.
        title: Add ${{ steps.parse-issue.outputs.SUBMISSION_NAME }} to the Qiskit Ecosystem
        body: |
          Nomination for: steps.parse-issue.outputs.SUBMISSION_NAME
          
          By @${{ github.event.issue.user.login }}, via #${{ github.event.issue.number }}

        branch: submission-${{ steps.parse-issue.outputs.SUBMISSION_SHORT_UUID }}
        labels: submission

    - name: Make comment on validated submission
      if: success() && ${{ steps.cpr.outputs.pull-request-number }}
      uses: peter-evans/create-or-update-comment@v5
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        edit-mode: replace
        body: |
          The submission is validated. Let's close this issue and start the conversation about this projectt in #${{ steps.cpr.outputs.pull-request-number }}.
          [Check out the logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ job.check_run_id }}).
          
          > [!NOTE]  
          > The submitted project is not yet approved. It will be once #${{ steps.cpr.outputs.pull-request-number }} is reviewed and merged. 

    - name: Close Issue
      run: gh issue close ${{ github.event.issue.number }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Make comment on failed submission
      if: failure()
      uses: peter-evans/create-or-update-comment@v5
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        edit-mode: replace
        body: |
          The submission failed.
          [Check out the logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ job.check_run_id }}).

          > [!TIP]
          > Edit the issue (using the ellipsis buttom on the right-upper corner) and try to fix the problems in the data validation.
          > The validation testing will re-run automtaically after that.
