name: Member validations

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened, ready_for_review, synchronize]

jobs:
  validate_candidate:
    name: Validate member update or new candidate
    if: >
      contains(github.event.pull_request.labels.*.name, 'member update') || (
      contains(github.event.pull_request.head.ref, 'submission')
      &&
      contains(github.event.pull_request.labels.*.name, 'submission')
      )
    runs-on: ubuntu-latest
    env:
      python-version: "3.13"
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - uses: actions/checkout@v6
      - name: Checkout PR
        run: |
          gh pr checkout ${{ github.event.pull_request.number }}
          git config --local user.email "qiskit-bot@users.noreply.github.com"
          git config --local user.name "qiskit-bot"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install taplo
        uses: uncenter/setup-taplo@v2
        with:
          version: "0.10.0"
      - name: Fetch member id
        id: get-id
        run: |
          id=$(echo ${{ github.event.pull_request.head.ref }} | cut -d- -f2 )
          echo "id=$id" >> $GITHUB_OUTPUT

      - name: Initial validatation
        run: python manager.py ci validate_member ${{ steps.get-id.outputs.id }} -e "activity, oss, recommendation, legacy, best_practice"  # There is no license yet

      - name: Create sections
        if: github.event.pull_request.draft == false
        run: python manager.py ci create_sections ${{ steps.get-id.outputs.id }}

      - name: Run taplo formater on TOML files
        run: taplo fmt resources/members/*.toml

      - name: Commit sections
        if: success()
        run: |
          if git diff --exit-code; then
            echo "No new sections to commit"
          else
            git commit -am "Update sections" --allow-empty
          fi
      - name: Fetch data
        if: github.event.pull_request.draft == false
        run: python manager.py ci update_member_data ${{ steps.get-id.outputs.id }}
      - name: Data validatation
        run: python manager.py ci validate_member ${{ steps.get-id.outputs.id }} -e "recommendation, legacy, best_practice"
      - name: Run taplo formater on TOML files
        run: taplo fmt resources/members/*.toml
      - name: Commit data
        if: success()
        run: |
          if git diff --exit-code; then
            echo "No new data to commit"
          else
            git commit -am "Update data" --allow-empty
          fi
      - name: Create badge
        if: github.event.review.state == 'approved'
        env:
          BITLY_TOKEN: ${{ secrets.BITLY_TOKEN }}
        run: python manager.py members update_badge

      - name: Run taplo formater on TOML files
        run: taplo fmt resources/members/*.toml

      - name: Commit badge
        if: success()
        run: |
          if git diff --exit-code; then
            echo "No badge to commit"
          else
            git commit -am "Update badge" --allow-empty
          fi
      - name: Push sections
        if: always()
        run: |
          git pull
          git push --verbose

