name: Fetch data for an unmerged member

on:
  pull_request_review:
    types: [submitted]

jobs:
  create_stats:
    if: >
      github.event.review.state == 'approved'
      && startsWith(github.event.pull_request.title, 'Add ')
      && contains(github.event.pull_request.labels.*.name, 'submission')
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Setup member id
        id: get-id
        run: |
          id=$(echo ${{ github.event.pull_request.head.ref }} | cut -d- -f2 )
          echo "::set-output name=id::$id"
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - uses: actions/checkout@v5
      - name: Checkout PR
        run: gh pr checkout ${{ github.event.pull_request.number }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update data
        run: |
          python ci fetch_new_member_data ${{ steps.get-id.outputs.id }}
      - name: Push stats
        if: success()
        run: |
          git commit -am "Update data on unmerged submission" --allow-empty
          git push --verbose
