name: Weekly | Update member badges

on:
  workflow_dispatch:
  schedule:
  - cron:  '0 9 * * 4'

jobs:
  batch_update_badges:
    name: "Update members badges"
    if: github.repository_owner == 'Qiskit'
    runs-on: ubuntu-latest
    steps:
    - name: Setup variables
      id: vars
      run: |
        echo "dateIseconds=$(date -Iseconds)" >> "$GITHUB_ENV"
        echo "date_bdY=$(date +'%b %d, %Y')" >> "$GITHUB_ENV"
        echo "pr_branch_name=batch_badges_$(date +'%Y_%m_%d_%H_%M')" >> "$GITHUB_ENV"
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
          python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Update maturity project
      run: python manager.py members update_maturity

    - name: Update checkups data
      run: python manager.py members update_checkups

    - name: Update Badge data
      env:
        BITLY_TOKEN: ${{ secrets.BITLY_TOKEN }}
      run: python manager.py members update_badge

    - name: Create PR for new badges
      id: cpr
      uses: peter-evans/create-pull-request@v7
      with:
        author: qiskit-bot <qiskit-bot@users.noreply.github.com>
        token: ${{ secrets.REPO_SCOPED_TOKEN }}
        commit-message: Member data update for ${{ env.dateIseconds }}
        title: Member data update for ${{ env.date_bdY }}
        body: |
          Member badge update
          when: ${{ env.dateIseconds }}
          ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        branch: ${{ env.pr_branch_name }}
        labels: member update
