name: Weekly | Update member status

on:
  workflow_dispatch:
  schedule:
  - cron:  '0 9 * * 4'

jobs:
  batch_update_status:
    name: "Update members status"
    if: github.repository_owner == 'Qiskit'
    runs-on: ubuntu-latest
    steps:
    - name: Setup variables
      id: vars
      run: |
        echo "dateIseconds=$(date -Iseconds)" >> "$GITHUB_ENV"
        echo "date_bdY=$(date +'%b %d, %Y')" >> "$GITHUB_ENV"
        echo "pr_branch_name=batch_status_$(date +'%Y_%m_%d_%H_%M')" >> "$GITHUB_ENV"
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
          python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install taplo
      uses: uncenter/setup-taplo@v2
      with:
        version: "0.10.0"

    - name: Update project maturity
      run: python manager.py members update_maturity

    - name: Update checkups
      run: python manager.py members update_checkups

    - name: Update status
      run: python manager.py members update_status

    - name: Run taplo formatter on TOML files
      run: taplo fmt resources/*.toml resources/members/*.toml

    - name: Create PR for status update
      id: cpr
      uses: peter-evans/create-pull-request@v7
      with:
        author: qiskit-bot <qiskit-bot@users.noreply.github.com>
        token: ${{ secrets.REPO_SCOPED_TOKEN }}
        commit-message: Member status update for ${{ env.dateIseconds }}
        title: Member status update for ${{ env.date_bdY }}
        body: |
          Member status update
          when: ${{ env.dateIseconds }}
          ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        branch: ${{ env.pr_branch_name }}
        labels: member update
