name: Ecosystem | New member

on:
  pull_request:
    types:
      - closed

jobs:
  if_new_member:
    if: github.event.pull_request.merged == true && contains(github.event.issue.labels.*.name, 'submission')
    runs-on: ubuntu-latest
    steps:
    - id: get-id
      run: |
        id=$(echo ${{github.event.pull_request.bodyText}} | grep "Nomination for" | cut -d: -f2- | awk '{$1=$1};1')
        echo "::set-output name=id::$id"
    - name: Create comment on success
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
              Hello @${{ github.event.issue.user.login }},

              **${{ steps.get-id.outputs.id }} is now part of the Qiskit Ecosystem**. Here are some follow up actions you can take to get the most out of the program:

              - :speech_balloon: Join other Qiskit ecosystem developers in the Slack [channel `#qiskit-ecosystem`](https://qiskit.slack.com/archives/C04RHE56N93). If you are not in the Qiskit workspace yet, sign up at https://qisk.it/join-slack
              - :white_check_mark: Use the [Qiskit theme](https://github.com/Qiskit/qiskit_sphinx_theme) for your documentation
              - :stethoscope: Keep an eye on the criteria compliance
              - :purple_heart: Add the [Qiskit Ecosystem badge](https://qisk.it/ecosystem-badges) to your `README.md`

              It is great to have you in the ecosystem.
